### ISSUE TITLE
Unable to run gallery example with qt backend

### ISSUE THREAD

**Issue by Sycration** [slint-ui/slint#1401] opened 2022-07-10 04:21 UTC
My `cargo.toml` is set to
```slint = {version = "0.2", default-features=false, features = ["backend-qt", "compat-0-2-0"]}```

```   Compiling p4n0l v0.1.0 (C:\Users\Sycration\Rust\p4n0l)
error[E0599]: no associated item named `FIELD_OFFSETS` found for struct `slint::re_exports::NativeStyleMetrics` in the current scope
    --> C:\Users\Sycration\Rust\p4n0l\target\debug\build\p4n0l-381261a460323bbe\out\gallery.rs:6885:50
     |
6885 | ...   (if r#NativeStyleMetrics :: FIELD_OFFSETS . r#dark_style . apply_pin (_self . root . get () . unwrap () . upgrade () . unwrap () . ...
     |                                   ^^^^^^^^^^^^^ associated item not found in `slint::re_exports::NativeStyleMetrics`

error[E0599]: no method named `init` found for struct `Pin<Rc<slint::re_exports::NativeStyleMetrics>>` in the current scope
     --> C:\Users\Sycration\Rust\p4n0l\target\debug\build\p4n0l-381261a460323bbe\out\gallery.rs:18046:71
      |
18046 |              inner . globals . global_NativeStyleMetrics . clone () . init (& inner) ;
      |                                                                       ^^^^ method not found in `Pin<Rc<slint::re_exports::NativeStyleMetrics>>`

error[E0599]: no function or associated item named `new` found for struct `slint::re_exports::NativeStyleMetrics` in the current scope
     --> C:\Users\Sycration\Rust\p4n0l\target\debug\build\p4n0l-381261a460323bbe\out\gallery.rs:18081:180
      |
18081 | ... r#NativeStyleMetrics :: new () , }
      |                             ^^^ function or associated item not found in `slint::re_exports::NativeStyleMetrics` ```

**Comment by ogoffart** [comment] 2022-07-10 09:08
Looks like an issue that is caused by Qt not being found.
Do you see a warning earlier in the compilation about Qt not being build?

(Regardless, i think it wasn't a good idea to use the NativeStyleMetrics directly from the non-native style for the dark-style. This is what is causing this compile time issue there, rather than a runtime panic explaining that there is no backend.)

**Comment by ogoffart** [comment] 2022-07-22 09:52
I just learned today that warning that we show in our build.rs script are actually not printed in the console because cargo don't print warning for dependencies from crates.io :-(

**Comment by ogoffart** [comment] 2023-04-14 12:47
Closing this issue as this is probably just a configuration issue.

**Closed by ogoffart** 2023-04-14 12:48 UTC
