### ISSUE TITLE
Chinese characters are displayed as a box on the WEB side

### ISSUE THREAD

**Issue by DLM8207** [slint-ui/slint#3631] opened 2023-10-10 02:59 UTC
When I started with "python -m http.server", the content of the web page was displayed abnormally, and the Chinese was changed into a box. But my desktop app is showing normally.
![web](https://github.com/slint-ui/slint/assets/3363625/7274f16f-8af9-482d-9f38-1ec81ce0ebf4)
![desktop](https://github.com/slint-ui/slint/assets/3363625/91494d6b-07df-4c83-9510-0f54ef12363b)
![Uploading web.png…]()

**Comment by ogoffart** [comment] 2023-10-10 07:15
Thanks for the bug report.

This is a known problem: https://github.com/slint-ui/slint/issues/2563
The default fonts don't cover the full range of character.

I think you can work around the problem by importing a font that has the characters

I'm closing this as a duplicate of #2563 but thanks anyway for reporting.

**Closed by ogoffart** 2023-10-10 07:15 UTC
