### ISSUE TITLE
font-size animation is broken

### ISSUE THREAD

**Issue by cppdev123** [slint-ui/slint#1334] opened 2022-06-11 16:47 UTC
font-size animation is broken (at least for Text) when adding font-size to animate and changing it the Text will remain in the same size I had to use a float property to animate it and bound the font-size to the value of this property multiplied by px

**Comment by hunger** [comment] 2022-06-17 18:53
Do you have a small example? I do not get what you are doing exactly.

**Comment by ogoffart** [comment] 2022-06-27 08:31
Looks like it is working.

I tried this example, and it animates:

```
_ := Text {
 text: "Hello World";
 font-size: 15px;
 animate font-size { duration: 1s; }
 TouchArea { clicked => { root.font-size = 50px; } }
}
```

[online editor](https://slint-ui.com/releases/0.2.4/editor/?snippet=_+%3A%3D+Text+%7B%0A+text%3A+%22Hello+World%22%3B%0A+font-size%3A+15px%3B%0A+animate+font-size+%7B+duration%3A+1s%3B+%7D%0A+TouchArea+%7B+clicked+%3D%3E+%7B+root.font-size+%3D+50px%3B+%7D+%7D%0A%7D)

**Comment by ogoffart** [comment] 2022-11-29 12:16
Closed as the bug cannot be reproduced

**Closed by ogoffart** 2022-11-29 12:16 UTC
Labels: font
