### ISSUE TITLE
two way binding to struct fields

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#556] opened 2021-10-07 15:03 UTC
Modify the Todo example like this:

```patch
diff --git a/examples/todo/cpp/main.cpp b/examples/todo/cpp/main.cpp
index bc614ca8..d203f353 100644
--- a/examples/todo/cpp/main.cpp
+++ b/examples/todo/cpp/main.cpp
@@ -30,13 +26,10 @@ int main()
     });

     demo->on_remove_done([todo_model] {
-        int offset = 0;
-        int count = todo_model->row_count();
-        for (int i = 0; i < count; ++i) {
-            if (todo_model->row_data(i - offset).checked) {
-                todo_model->erase(i - offset);
-                offset += 1;
-            }
+        for (auto i = 0; i < todo_model->row_count(); ++i) {
+            auto todo = todo_model->row_data(i);
+            todo.checked = true;
+            todo_model->set_row_data(i, todo);
         }
     });

diff --git a/examples/todo/rust/main.rs b/examples/todo/rust/main.rs
index b29ef759..9738caf6 100644
--- a/examples/todo/rust/main.rs
+++ b/examples/todo/rust/main.rs
@@ -42,12 +42,10 @@ pub fn main() {
     main_window.on_remove_done({
         let todo_model = todo_model.clone();
         move || {
-            let mut offset = 0;
             for i in 0..todo_model.row_count() {
-                if todo_model.row_data(i - offset).checked {
-                    todo_model.remove(i - offset);
-                    offset += 1;
-                }
+                let mut bulb = todo_model.row_data(i);
+                bulb.checked = true;
+                todo_model.set_row_data(i, bulb);
             }
         }
     });
```

Then when running, pressing the "remove all done" button will toggle all todos. That works the first time. Then turn off a few toggles in the UI and press the "remove all done" button again.

Expected Result: All todos are checked again.
Actual Result: Nothing changes in the UI.

**Comment by tronical** [comment] 2021-10-08 10:20
At the heart of the issue lies that the binding for the checked property is destroyed:

```60
CheckBox {
    text: todo.title;
    checked: todo.checked;
    toggled => {
        todo.checked = checked;
    }
}
```

Initially the binding `checked: todo.checked;` correctly fetches the data out of the model (`model_data` property). But when the user clicks on the `CheckBox`, the style runs this code in the `TouchArea`:

```60
touch := TouchArea {
        clicked => {
            if (root.enabled) {
                root.checked = !root.checked;
                root.toggled();
            }
        }
    }
```

and the assignment to `root.checked` destroys the data model binding.

**Comment by levrik** [comment] 2022-05-20 13:08
@ogoffart I was just hit by this as well. Is there some suggested workaround for now? I can't control the `checked` property of a `CheckBox` from Rust anymore as soon as it was toggled once.

**Comment by ogoffart** [comment] 2022-05-20 14:12
> Is there some suggested workaround for now?

It depends a bit of what you're doing.
But we can use a workaround similar to the missing changed event https://github.com/slint-ui/slint/issues/112#issuecomment-1065866865

```rust
      CheckBox {
            text: {
                checked = the_property;    // <- Ugly workaround right there        
                " Check me ";
            }
            checked: the_property;
            toggled => {
                the_property = checked;
            }
        }
```

[code editor link of example](https://slint-ui.com/releases/0.2.4/editor/?snippet=%0Aimport+%7B+CheckBox%2C+Button%2C+VerticalBox%7D+from+%22std-widgets.slint%22%3B%0Aexport+Demo+%3A%3D+Window+%7B%0A%0A++++property+%3Cbool%3E+the_property%3B%0A%0A++++VerticalBox+%7B%0A++++++++%0A++++++++alignment%3A+start%3B%0A++++++++CheckBox+%7B%0A++++++++++++text%3A+%7B%0A++++++++++++++++checked+%3D+the_property%3B++++++++++++%0A++++++++++++++++%22+Check+me+%22%3B%0A++++++++++++%7D%0A++++++++++++checked%3A+the_property%3B%0A++++++++++++toggled+%3D%3E+%7B%0A++++++++++++++++the_property+%3D+checked%3B%0A++++++++++++%7D%0A++++++++%7D%0A++++++++Button+%7B%0A++++++++++++text%3A+%22toggle%22%3B%0A++++++++++++clicked+%3D%3E+%7B+the_property+%3D+%21the_property%3B+%7D%0A++++++++%7D%0A++++%7D%0A%7D%0A)

This works because the `text` property is evaluated (indirectly) by the rendering engine. And it depends on the `the_property` and do side effect in a binding (which is supposed to be pure, but nobody is checking).

**Comment by levrik** [comment] 2022-05-20 14:28
@ogoffart I see. I worked around by using my local fork and slightly modifying `CheckBox`s implementation.
I could propose this change in a PR when I have a free moment.

**Comment by ogoffart** [comment] 2022-11-29 11:14
Closing this as a duplicate of https://github.com/slint-ui/slint/issues/814

**Closed by ogoffart** 2022-11-29 11:14 UTC
Labels: enhancement
