### ISSUE TITLE
Crashed due to ComboBox when clicking it

### ISSUE THREAD

**Issue by wuanzhuan** [slint-ui/slint#5558] opened 2024-07-05 14:40 UTC
I think  because of the ComboBox is in PopupWindow. slint version is 1.60. recurrent in slintpad as follows:
```slint
import { Button, Palette, Switch, ComboBox, ListView, VerticalBox, HorizontalBox } from "std-widgets.slint";

export component LogConfig {
    callback selected_level(/*level*/string);

    button := Button {
        width: self.preferred-width;
        height: self.preferred-height;
        text: @tr("Log Config");
        clicked => {
            popup.show()
        }
    }

    popup := PopupWindow {
        y: button.height + 4mm;
        close-on-click: false;

        Rectangle {
            background: Palette.background;
            border-width: 2px;
            border-color: Palette.border;

            VerticalBox {
                HorizontalLayout {
                    height: self.preferred-height;
                    alignment: end;

                    Button {
                        padding: 0px;
                        width: self.preferred-width;
                        height: self.preferred-height;
                        text: "X";

                        clicked => {
                            popup.close();
                        }
                    }
                }
                VerticalBox {
                    HorizontalBox {
                        height: self.preferred-height;
                        alignment: start;

                        Text {
                            vertical-alignment: center;
                            text: @tr("level: ");
                        }
                        ComboBox {
                            model: ["trace", "debug", "info", "warn", "error"];
                            current-value: "trace";
                            selected(value) => {
                                selected_level(value)
                            }
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by ogoffart** [comment] 2024-07-08 15:14
Thanks for filling an issue.

This is a duplicate of issue #4300 (which seems to be caused by https://github.com/slint-ui/slint/issues/4356 )
I'm closing this issue as duplicate, thanks anyway for taking the time to report the issue and please :+1: that issue.

**Closed by ogoffart** 2024-07-08 15:14 UTC
