### ISSUE TITLE
language server crashed

### ISSUE THREAD

**Issue by vede1** [slint-ui/slint#5038] opened 2024-04-10 16:07 UTC
```
export component R1 inherits Rectangle {
    t := TouchArea { }

    states [
        hover when t.has-hover: {
            background: white;
        }
    ]
}

export component R2 inherits R1 { }

export component AppWindow inherits Window {
    R2 {
        states [
            s1 when mp.visible: {
                background: white;
            }
        ]

        mp := Rectangle {
            visible: false;
        }
    }
}
```
```
thread 'main' panicked at internal/interpreter/eval.rs:1398:71:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 6:02:39 PM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
```

**Comment by ogoffart** [comment] 2024-04-12 12:52
Duplicate of https://github.com/slint-ui/slint/issues/1461
The issue is fairly hard to solve and will need some refactoring of the compiler to solve it.
Marking as duplicated, but thanks anyway for reporting.

**Comment by ogoffart** [comment] 2024-04-12 12:54
Actually, re-opening because the panic could get fixed and replaced by an error just like we did for the original testcase of #1461

**Closed** 2024-04-12 13:53 UTC
Labels: bug, a:compiler
