### ISSUE TITLE
slint always opening a console window on app start

### ISSUE THREAD

**Issue by sedan-cell** [slint-ui/slint#5269] opened 2024-05-18 21:33 UTC
using windows 11 and slint 1.6.0 i compiled my application in release mode. when i run it by double clicking the exe not only is the app shown, but a console window behind it. i think its for slint errors but there are none. this is confusing and non-documented behavior especially for less tech savvy users.

**Comment by tronical** [comment] 2024-05-19 07:44
Duplicate of #3235

**Comment by tronical** [comment] 2024-05-19 07:44
I’m curious, is there a place where in the docs you’d look for it?

**Closed by tronical** 2024-05-19 07:44 UTC
