### ISSUE TITLE
Crash in preview with nested PopupWindow

### ISSUE THREAD

**Issue by otiv-willem-vanhulle** [slint-ui/slint#6236] opened 2024-09-20 12:30 UTC
There is a bug in the Slint preview code that makes it crash when you use a popupwindow inside a popupwindow. I have tried replacing the popupwindow by rectangle but it still crashes.

```slint

import { Button } from "std-widgets.slint";


export component FullScreenBackground inherits Rectangle {
    callback close();
    background: black;
    opacity: 0.5;
    z: 0;
    click_outside_area := TouchArea {
        clicked => {
            root.close();
        }
        @children
    }
}

export component DialogBackground inherits Rectangle {
    z: 1;
    TouchArea {
        clicked => {
        }
    }

    @children
}

export component Popup inherits PopupWindow {
    in property <brush> underlay_color: black;

    close-on-click: false;

    underlay := FullScreenBackground {
        background: underlay_color;
        close => {
            root.close();
        }
    }

    VerticalLayout {
        alignment: center;
        HorizontalLayout {
            alignment: center;

            overlay := DialogBackground {
                @children
            }
        }
    }
}

component TestNestedModalDialog inherits Window {
    height: 200px;
    width: 200px;
    Rectangle {
        Button {
            text: "Show Modal";
            clicked => {
                first_dialog.show()
            }
        }

        first_dialog := Popup {
            height: root.height;
            width: root.width;

            Rectangle {
                background: red;

                Button {
                    text: "Show second dialog";
                    clicked => {
                        second_dialog.show()
                    }
                }

                second_dialog := Popup {
                    height: root.height;
                    width: root.width;

                    Rectangle {
                        background: yellow;
                        Text {
                            text: "Second dialog";
                        }
                    }
                }
            }
        }
    }
}
```

This is a [link](https://slintpad.com/?snippet=%0Aimport+%7B+Button+%7D+from+%22std-widgets.slint%22%3B%0A%0A%0Aexport+component+FullScreenBackground+inherits+Rectangle+%7B%0A++++callback+close%28%29%3B%0A++++background%3A+black%3B%0A++++opacity%3A+0.5%3B%0A++++z%3A+0%3B%0A++++click_outside_area+%3A%3D+TouchArea+%7B%0A++++++++clicked+%3D%3E+%7B%0A++++++++++++root.close%28%29%3B%0A++++++++%7D%0A++++++++%40children%0A++++%7D%0A%7D%0A%0Aexport+component+DialogBackground+inherits+Rectangle+%7B%0A++++z%3A+1%3B%0A++++TouchArea+%7B%0A++++++++clicked+%3D%3E+%7B%0A++++++++%7D%0A++++%7D%0A%0A++++%40children%0A%7D%0A%0Aexport+component+Popup+inherits+PopupWindow+%7B%0A++++in+property+%3Cbrush%3E+underlay_color%3A+black%3B%0A%0A++++close-on-click%3A+false%3B%0A%0A++++underlay+%3A%3D+FullScreenBackground+%7B%0A++++++++background%3A+underlay_color%3B%0A++++++++close+%3D%3E+%7B%0A++++++++++++root.close%28%29%3B%0A++++++++%7D%0A++++%7D%0A%0A++++VerticalLayout+%7B%0A++++++++alignment%3A+center%3B%0A++++++++HorizontalLayout+%7B%0A++++++++++++alignment%3A+center%3B%0A%0A++++++++++++overlay+%3A%3D+DialogBackground+%7B%0A++++++++++++++++%40children%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A%7D%0A%0Acomponent+TestNestedModalDialog+inherits+Window+%7B%0A++++height%3A+200px%3B%0A++++width%3A+200px%3B%0A++++Rectangle+%7B%0A++++++++Button+%7B%0A++++++++++++text%3A+%22Show+Modal%22%3B%0A++++++++++++clicked+%3D%3E+%7B%0A++++++++++++++++first_dialog.show%28%29%0A++++++++++++%7D%0A++++++++%7D%0A%0A++++++++first_dialog+%3A%3D+Popup+%7B%0A++++++++++++height%3A+root.height%3B%0A++++++++++++width%3A+root.width%3B%0A%0A++++++++++++Rectangle+%7B%0A++++++++++++++++background%3A+red%3B%0A%0A++++++++++++++++Button+%7B%0A++++++++++++++++++++text%3A+%22Show+second+dialog%22%3B%0A++++++++++++++++++++clicked+%3D%3E+%7B%0A++++++++++++++++++++++++second_dialog.show%28%29%0A++++++++++++++++++++%7D%0A++++++++++++++++%7D%0A%0A++++++++++++++++second_dialog+%3A%3D+Popup+%7B%0A++++++++++++++++++++height%3A+root.height%3B%0A++++++++++++++++++++width%3A+root.width%3B%0A%0A++++++++++++++++++++Rectangle+%7B%0A++++++++++++++++++++++++background%3A+yellow%3B%0A++++++++++++++++++++++++Text+%7B%0A++++++++++++++++++++++++++++text%3A+%22Second+dialog%22%3B%0A++++++++++++++++++++++++%7D%0A++++++++++++++++++++%7D%0A++++++++++++++++%7D%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A%7D%0A&style=native) to the Slintpad.

**Comment by ogoffart** [comment] 2024-09-21 05:41
This is actually a duplicate of https://github.com/slint-ui/slint/issues/4300
Currently we can only have one open Popup (https://github.com/slint-ui/slint/issues/4356)
I'm going to close as duplicate, but thanks anyway for reporting.

**Closed by ogoffart** 2024-09-21 05:41 UTC
