### ISSUE TITLE
Text in TextInput element disappears when there's no wrapping opportunity

### ISSUE THREAD

**Issue by cauliflowew** [slint-ui/slint#1127] opened 2022-03-31 13:00 UTC
In the `TextInput` element whenever there's no wrapping opportunity (for example if you type a 100 letters together without spaces), then the text will not be wrapped onto multiple lines, but will just disappear. Example below:

https://user-images.githubusercontent.com/82113833/161060443-70b66d45-fa0f-4932-b83c-6c13069efaa6.mov

**Comment by ogoffart** [comment] 2022-03-31 13:23
Thanks for the bug report.

This is a duplicate of #843

And maybe related to #985 as well?

**Comment by tronical** [comment] 2022-04-19 13:22
Closing this as I believe this is fixed as per #843

**Closed by tronical** 2022-04-19 13:22 UTC
Labels: duplicate
