### ISSUE TITLE
ComboBox: different behaviour on windows/linux

### ISSUE THREAD

**Issue by newfla** [slint-ui/slint#6785] opened 2024-11-14 10:57 UTC
I'm experiencing a different behavior of the ComboBox between Windows and Linux.
When it is positioned as the last item (vertically) of a window, the selection popup on Windows is truncated while on Gnome (47 wayland session) it is shown outside the window.
Is this expected behavior?
It might be nice to be able to decide if the popup should be shown above or below the box.
- Windows
![Windows ComboBox](https://github.com/user-attachments/assets/291bb9bc-fbe9-46ba-8a37-0e263205c835)
- Linux
- ![linux ComboBox](https://github.com/user-attachments/assets/a825db3c-7ea0-48a6-b907-539d4599b5e5)

[Reproducible example](https://github.com/newfla/daily-strip/blob/main/src/frontend/slint-ui/main.slint)

**Comment by Enyium** [comment] 2024-11-15 00:28
I believe there was a PR recently that repositioned the `ComboBox` pop-up, so everything becomes visible (maybe try the master branch?). But, in the future, such pop-ups should be (frameless) topmost top-level windows, just like in other apps, so they can be drawn outside the window that contains their associated unopened widget.

**Comment by ogoffart** [comment] 2024-11-15 08:59
That's right. The problem is that the winit backend doesn't support popup as window (unlike the Qt backend.)
This is a duplicate of https://github.com/slint-ui/slint/issues/2375. Closing as such, but thanks anyway for filing a bug.

In the master branch we do change the position of the popup such that it stays visible.

**Closed by ogoffart** 2024-11-15 08:59 UTC

**Comment by newfla** [comment] 2024-11-15 09:20
Master works fine. I'm looking forward to 1.9.0 release 🤩
![master test ](https://github.com/user-attachments/assets/40774d3f-eadf-44bf-bf9e-81c7415d0633)
