### ISSUE TITLE
How to build the developed program as an installation package？

### ISSUE THREAD

**Issue by ZtionJam** [slint-ui/slint#3633] opened 2023-10-10 06:15 UTC
How do you take a developed program and build it as an installation package, like '.exe' or '.msi' or '.dmg' for mac

**Comment by tronical** [comment] 2023-10-10 06:25
We were just recently made aware of this super cool project to address this gap: https://github.com/crabnebula-dev/cargo-packager/tree/main

I wonder how to integrate that into our docs.

**Comment by ogoffart** [comment] 2024-01-15 18:10
There is also cargo-bundle https://github.com/burtonageo/cargo-bundle

Anyway, this is outside of the scope of Slint.
Although our documentation could refer to these project perhaps

**Comment by tronical** [comment] 2024-01-23 13:21
Duplicate of #4408 - closing in favor of the other issue.

**Comment by tronical** [comment] 2024-01-23 13:21
Duplicate of #4408

**Closed by tronical** 2024-01-23 13:21 UTC
Labels: a:documentation
