### ISSUE TITLE
是否可以增加一个文本高亮的控件

### ISSUE THREAD

**Issue by coder163** [slint-ui/slint#7163] opened 2024-12-19 07:09 UTC
### Feature Description

我在尝试制作一款笔记软件，使用的TextEdit可惜slint不支持文本框的语法高亮，搞的我很无奈，没想到slint升级了但是依旧没有支持，同时TabWidget中的Tab不应该是可以关闭的吗

**Comment by tronical** [comment] 2024-12-19 07:42
I ran this through google translate... Could it be that what you're looking for is the same as #2723 ?

**Comment by coder163** [comment] 2024-12-19 08:07
> I ran this through google translate... Could it be that what you're looking for is the same as #2723 ?

This is the reply from machine translation. I just looked at it and yes, that's what I want to do. I can set its style through CSS, but I don't know when the official support will be available

**Comment by tronical** [comment] 2024-12-19 08:10
Thanks for the quick reply. Yes, we need to implement rich text support and an API to specify the formatting. I'll close this then.

**Comment by tronical** [comment] 2024-12-19 08:10
Duplicate of #2723

**Closed by tronical** 2024-12-19 08:10 UTC
Labels: enhancement, need triaging

**Comment by coder163** [comment] 2024-12-19 08:13
> Thanks for the quick reply. Yes, we need to implement rich text support and an API to specify the formatting. I'll close this then.

Close it, thank you for your reply. I would like to know how long it will be expected to be implemented in future versions

**Comment by tronical** [comment] 2024-12-19 08:38
I don't know, unfortunately. We tend to develop features based on the needs of our commercial customers.
