### ISSUE TITLE
crash when turning on edit mode in live-preview

### ISSUE THREAD

**Issue by szecket** [slint-ui/slint#6529] opened 2024-10-13 06:26 UTC
thread 'main' panicked at /Users/runner/work/slint/slint/internal/core/model.rs:929:38:
already borrowed: BorrowMutError
stack backtrace:
   0:        0x10558959c - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h243268f17d714c7f
   1:        0x104e70a9c - core::fmt::write::hb3cfb8a30e72d7ff
   2:        0x1055630cc - std::io::Write::write_fmt::hfb2314975de9ecf1
   3:        0x10558d5cc - std::panicking::default_hook::{{closure}}::h14c7718ccf39d316
   4:        0x10558d01c - std::panicking::default_hook::hc62e60da3be2f352
   5:        0x10551a1e8 - slint_lsp::main::{{closure}}::h4038def7d45e7862
   6:        0x10558ed70 - std::panicking::rust_panic_with_hook::h09e8a656f11e82b2
   7:        0x10558dfc4 - std::panicking::begin_panic_handler::{{closure}}::h1230eb3cc91b241c
   8:        0x10558df38 - std::sys::backtrace::__rust_end_short_backtrace::hc3491307aceda2c2
   9:        0x10558df2c - _rust_begin_unwind
  10:        0x105ae35f8 - core::panicking::panic_fmt::ha4b80a05b9fff47a
  11:        0x105ae38e4 - core::cell::panic_already_borrowed::h6986b058cdb2041a
  12:        0x104d88750 - <slint_lsp::preview::ui::slint_generatedPreviewUi::InnerComponent_empty_402 as i_slint_core::item_tree::ItemTree_vtable_mod::ItemTree>::get_subtree::hea65bc1598fdca3e
  13:        0x10509786c - i_slint_core::item_tree::ItemRc::next_focus_item::{{closure}}::h37ed6e2048a2f735
  14:        0x1050967d4 - i_slint_core::item_tree::ItemRc::move_focus::h2c1a5b0f925c69d6
  15:        0x10510cb08 - i_slint_core::window::WindowInner::move_focus::h8fd334bd78911897
  16:        0x10510d014 - i_slint_core::window::WindowInner::set_focus_item::hb118181484a58aec
  17:        0x104d83b88 - <slint_lsp::preview::ui::slint_generatedPreviewUi::InnerComponent_empty_405 as i_slint_core::model::RepeatedItemTree>::init::he745ceff529320b2
  18:        0x104d85e88 - <slint_lsp::preview::ui::slint_generatedPreviewUi::InnerComponent_empty_402 as i_slint_core::item_tree::ItemTree_vtable_mod::ItemTree>::visit_children_item::visit_dynamic::h55177a39d2855b3d
  19:        0x104d859c8 - <slint_lsp::preview::ui::slint_generatedPreviewUi::InnerComponent_empty_402 as i_slint_core::item_tree::ItemTree_vtable_mod::ItemTree>::visit_children_item::hbba6c0785a07c06d
  20:        0x10512b9f0 - i_slint_core::item_tree::ItemVisitor_vtable_mod::ItemVisitorVTable::new::visit_item::h7ec1997eb8ce86f7
  21:        0x104d85914 - <slint_lsp::preview::ui::slint_generatedPreviewUi::InnerComponent_empty_402 as i_slint_core::item_tree::ItemTree_vtable_mod::ItemTree>::visit_children_item::hbba6c0785a07c06d
  22:        0x105380a70 - i_slint_core::model::Repeater<C>::visit::h81f130900ce45e0f
  23:        0x104df3b18 - <slint_lsp::preview::ui::slint_generatedPreviewUi::InnerComponent_rectangle_9 as i_slint_core::item_tree::ItemTree_vtable_mod::ItemTree>::visit_children_item::visit_dynamic::hce294e3db7dc0a91
  24:        0x104df23fc - <slint_lsp::preview::ui::slint_generatedPreviewUi::InnerComponent_rectangle_9 as i_slint_core::item_tree::ItemTree_vtable_mod::ItemTree>::visit_children_item::h61f141ae0a4e6da2
  25:        0x10512b9f0 - i_slint_core::item_tree::ItemVisitor_vtable_mod::ItemVisitorVTable::new::visit_item::h7ec1997eb8ce86f7
  26:        0x104df23a8 - <slint_lsp::preview::ui::slint_generatedPreviewUi::InnerComponent_rectangle_9 as i_slint_core::item_tree::ItemTree_vtable_mod::ItemTree>::visit_children_item::h61f141ae0a4e6da2
  27:        0x10512b9f0 - i_slint_core::item_tree::ItemVisitor_vtable_mod::ItemVisitorVTable::new::visit_item::h7ec1997eb8ce86f7
  28:        0x104df23a8 - <slint_lsp::preview::ui::slint_generatedPreviewUi::InnerComponent_rectangle_9 as i_slint_core::item_tree::ItemTree_vtable_mod::ItemTree>::visit_children_item::h61f141ae0a4e6da2
  29:        0x10512b9f0 - i_slint_core::item_tree::ItemVisitor_vtable_mod::ItemVisitorVTable::new::visit_item::h7ec1997eb8ce86f7
  30:        0x104df23a8 - <slint_lsp::preview::ui::slint_generatedPreviewUi::InnerComponent_rectangle_9 as i_slint_core::item_tree::ItemTree_vtable_mod::ItemTree>::visit_children_item::h61f141ae0a4e6da2
  31:        0x10512b9f0 - i_slint_core::item_tree::ItemVisitor_vtable_mod::ItemVisitorVTable::new::visit_item::h7ec1997eb8ce86f7
  32:        0x104df23a8 - <slint_lsp::preview::ui::slint_generatedPreviewUi::InnerComponent_rectangle_9 as i_slint_core::item_tree::ItemTree_vtable_mod::ItemTree>::visit_children_item::h61f141ae0a4e6da2
  33:        0x10512b9f0 - i_slint_core::item_tree::ItemVisitor_vtable_mod::ItemVisitorVTable::new::visit_item::h7ec1997eb8ce86f7
  34:        0x104df23a8 - <slint_lsp::preview::ui::slint_generatedPreviewUi::InnerComponent_rectangle_9 as i_slint_core::item_tree::ItemTree_vtable_mod::ItemTree>::visit_children_item::h61f141ae0a4e6da2
  35:        0x10512b9f0 - i_slint_core::item_tree::ItemVisitor_vtable_mod::ItemVisitorVTable::new::visit_item::h7ec1997eb8ce86f7
  36:        0x104df23a8 - <slint_lsp::preview::ui::slint_generatedPreviewUi::InnerComponent_rectangle_9 as i_slint_core::item_tree::ItemTree_vtable_mod::ItemTree>::visit_children_item::h61f141ae0a4e6da2
  37:        0x10512b9f0 - i_slint_core::item_tree::ItemVisitor_vtable_mod::ItemVisitorVTable::new::visit_item::h7ec1997eb8ce86f7
  38:        0x104df23a8 - <slint_lsp::preview::ui::slint_generatedPreviewUi::InnerComponent_rectangle_9 as i_slint_core::item_tree::ItemTree_vtable_mod::ItemTree>::visit_children_item::h61f141ae0a4e6da2
  39:        0x10512b9f0 - i_slint_core::item_tree::ItemVisitor_vtable_mod::ItemVisitorVTable::new::visit_item::h7ec1997eb8ce86f7
  40:        0x104df2348 - <slint_lsp::preview::ui::slint_generatedPreviewUi::InnerComponent_rectangle_9 as i_slint_core::item_tree::ItemTree_vtable_mod::ItemTree>::visit_children_item::h61f141ae0a4e6da2
  41:        0x104df962c - <slint_lsp::preview::ui::slint_generatedPreviewUi::InnerPreviewUi as i_slint_core::item_tree::ItemTree_vtable_mod::ItemTree>::visit_children_item::visit_dynamic::ha412ac6487b6b2ed
  42:        0x104df8bc4 - <slint_lsp::preview::ui::slint_generatedPreviewUi::InnerPreviewUi as i_slint_core::item_tree::ItemTree_vtable_mod::ItemTree>::visit_children_item::hcb9cc77c6c13d154
  43:        0x10512b9f0 - i_slint_core::item_tree::ItemVisitor_vtable_mod::ItemVisitorVTable::new::visit_item::h7ec1997eb8ce86f7
  44:        0x104df8b10 - <slint_lsp::preview::ui::slint_generatedPreviewUi::InnerPreviewUi as i_slint_core::item_tree::ItemTree_vtable_mod::ItemTree>::visit_children_item::hcb9cc77c6c13d154
  45:        0x10516ac94 - i_slint_renderer_skia::SkiaRenderer::render_to_canvas::{{closure}}::h5e02fd45c3e7e21f
  46:        0x10516d894 - i_slint_renderer_skia::SkiaRenderer::render_to_canvas::haf3749075e48ad49
  47:        0x105170a88 - <i_slint_renderer_skia::metal_surface::MetalSurface as i_slint_renderer_skia::Surface>::render::h8ecc6b53329ed167
  48:        0x104ed20dc - <i_slint_backend_winit::renderer::skia::WinitSkiaRenderer as i_slint_backend_winit::renderer::WinitCompatibleRenderer>::render::h0ad7bad42dfbf3f0
  49:        0x104eb3394 - i_slint_backend_winit::winitwindowadapter::WinitWindowAdapter::draw::h1a3a5d7133bf7609
  50:        0x104ecd18c - <i_slint_backend_winit::event_loop::ActiveEventLoopSetterDuringEventProcessing<Handler> as winit::application::ApplicationHandler<Event>>::window_event::h5224194e9fcc2ff2
  51:        0x104ee6db8 - winit::platform_impl::macos::event_loop::map_user_event::{{closure}}::h9c6d6fa70ec4a2dd
  52:        0x105659460 - winit::platform_impl::macos::event_handler::EventHandler::handle_event::hcc603808dda17aa5
  53:        0x105656a2c - winit::platform_impl::macos::observer::control_flow_end_handler::he142affafe0280b7
  54:        0x19cf7d254 - <unknown>
  55:        0x19cf7d140 - <unknown>
  56:        0x19cf7c868 - <unknown>
  57:        0x19cf7be0c - <unknown>
  58:        0x1a7717000 - <unknown>
  59:        0x1a7716e3c - <unknown>
  60:        0x1a7716b94 - <unknown>
  61:        0x1a07d4970 - <unknown>
  62:        0x1a0fc6dec - <unknown>
  63:        0x1a07c7cb8 - <unknown>
  64:        0x104ee4f68 - <i_slint_backend_winit::Backend as i_slint_core::platform::Platform>::run_event_loop::ha76991eba2dd7206
  65:        0x1054638dc - slint_lsp::preview::native::start_ui_event_loop::h65ac625c29c979e7
  66:        0x105518d1c - slint_lsp::main::ha0eaa1a8aa4a063b
  67:        0x10546b7e8 - std::sys::backtrace::__rust_begin_short_backtrace::h4b05c3596b27acee
  68:        0x105516f58 - _main
[Info  - 2:24:36 AM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug. Please open an issue on https://github.com/slint-ui/slint/issues

**Comment by szecket** [comment] 2024-10-13 06:30
specifically when selecting "AboutSlint" in the sidebar of the demo
v2024.10.1112 of live-preview

**Comment by ogoffart** [comment] 2024-10-14 11:41
I'm pretty sure this is duplicate of https://github.com/slint-ui/slint/issues/3725 / https://github.com/slint-ui/slint/pull/3215

**Comment by ogoffart** [comment] 2024-11-07 08:44
Closing as duplicate of https://github.com/slint-ui/slint/issues/3214

**Closed by ogoffart** 2024-11-07 08:44 UTC
Labels: bug
