### ISSUE TITLE
Parallel build on Windows fails

### ISSUE THREAD

**Issue by tilladam** [slint-ui/slint#126] opened 2020-12-08 10:00 UTC
When building on Windows with MSVC and /maxcpucount:X for X>1 the build breaks trying to replace corrosion-generator.exe while it is opened by another process, which is not possible on Windows. Limiting the build to 1 core works around the issue. I'm not sure why that binary is regenerated on every build anyway, but that is orthogonal.

**Comment by tronical** [comment] 2021-01-28 14:07
I've been trying to reproduce this but haven't been able to yet. I'm using MSVC 2019, configured with plain `cmake \path\to\sixtyfps-src` in a x64 "shell". Subsequently then the build with `msbuild /maxcpucount:4 ALL_BUILD.vcxproj` or `cmake --build . --parallel` runs through in many attempts.

Do you happen to remember what command exactly you were using to trigger the build?

It's also odd that you say that the binary is generated on every build. Does that mean that you don't see a "null" build but it will always compile something (`generator.exe`) ?

**Comment by ogoffart** [comment] 2022-11-29 09:39
We were not able to reproduce this issue and nobody else complained. 
So i'm going to close this issue.

**Closed by ogoffart** 2022-11-29 09:39 UTC
Labels: question
