### ISSUE TITLE
Documentation jumps multiple times during loading with incorrect target position

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#6023] opened 2024-09-01 09:50 UTC
Links to the Slint documentation with `#` part jump multiple times after initial page visit and end up at an incorrect position:

https://github.com/user-attachments/assets/260313fe-ec58-402a-a51b-f993706854a6

This seems to be associated with the many examples embedded on the page.

Link: https://releases.slint.dev/1.7.2/docs/slint/src/language/builtins/elements#popupwindow

**Comment by ogoffart** [comment] 2024-09-09 09:10
I bet this is caused by the wasm preview somehow changing the size of the page. I have no idea how we can fix that.
We discussed earlier to have separate pages for each element which would work around it in this case, but not in the general case.

**Comment by NigelBreslaw** [comment] 2024-09-09 19:44
I will take this as part of the docs update. Lots of things could be causing this kind of layout thrashing and it makes the docs significantly harder to use.

**Comment by NigelBreslaw** [comment] 2024-12-09 07:56
@Enyium I'm going to close this as the new docs solve the issue. https://snapshots.slint.dev/master/docs/slint/

This is solved by moving from Sphinx to Starlight as the docs framework. Then more items are broken onto separate pages and finally things like the <Image> and other components are designed to avoid the kind of content layout shifts that break navigation or cause the general page to move around on load.

**Closed by NigelBreslaw** 2024-12-09 07:56 UTC
Labels: bug, a:documentation
