### ISSUE TITLE
`transparent` `Window` `background` rendered black

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#6020] opened 2024-09-01 07:41 UTC
I'm on Windows 10 using Rust.

With Skia, when using the Cargo feature `"renderer-skia"`, but not when using the feature `"renderer-skia-opengl"` or the software or FemtoVG renderer, a `Window` with `background: transparent;` is rendered black:

![transparent-as-black](https://github.com/user-attachments/assets/a5938054-7b01-4408-b803-7ae3f8aa0935)

Correctly rendered (like with `"renderer-skia-opengl"`), it looks like this:

![transparent](https://github.com/user-attachments/assets/0d51169c-39e1-4ae3-afd2-529deb21425f)

Maybe, this is a problem like in #5765 where experiences differ on different machines.

@Horbin-Magician, since you commented in the other issue that you encountered even worse problems, would you please check how this bug manifests for you? Change the `Cargo.toml` features and `env!()` calls in `main.rs`.

Demo project: [slint-test.zip](https://github.com/user-attachments/files/16827824/slint-test.zip)

**Comment by Horbin-Magician** [comment] 2024-09-01 09:14
Because the device having problem is my user's device, I can't test it in detail.
No matter using FemtoVG, renderer-skia, or renderer-skia-opengl, the "transparent" dosen't work.
When using renderer-skia-opengl, it having the some problem as https://github.com/slint-ui/slint/issues/5765.

It's very hard to pinpoint where the problem lies, because different devices behave differently.
I'm now banking on newer rendering solutions, such as using the WGPU to solve all these problems :(

**Comment by tronical** [comment] 2024-09-12 15:53
Duplicate of #4120

**Closed** 2024-09-12 15:54 UTC
Labels: a:renderer-skia
