### ISSUE TITLE
Slint LSP panicked: `Cannot parse URL for file`

### ISSUE THREAD

**Issue by eugenwintersberger** [slint-ui/slint#4338] opened 2024-01-13 21:26 UTC
Hi folks,
 I am using the VSCode Slint extension and have some issues with the LSP for the slint DSL. The LSP craches with the following error message:

```
thread 'LanguageServer' panicked at tools/lsp/language/completion.rs:637:42:
Cannot parse URL for file '"src/bin/test1/ui/network.slint"'
stack backtrace:
   0:     0x559a6e65cc5f - std::backtrace_rs::backtrace::libunwind::trace::h67a838aed1f4d6ec
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x559a6e65cc5f - std::backtrace_rs::backtrace::trace_unsynchronized::h1d1786bb1962baf8
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x559a6e65cc5f - std::sys_common::backtrace::_print_fmt::h5a0b1f807a002d23
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x559a6e65cc5f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf84ab6ad0b91784c
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x559a6dec7d3c - core::fmt::rt::Argument::fmt::h28f463bd1fdabed5
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/rt.rs:138:9
   5:     0x559a6dec7d3c - core::fmt::write::ha37c23b175e921b3
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/mod.rs:1114:21
   6:     0x559a6e622f5d - std::io::Write::write_fmt::haa1b000741bcbbe1
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/io/mod.rs:1763:15
   7:     0x559a6e65e32e - std::sys_common::backtrace::_print::h1ff1030b04dfb157
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x559a6e65e32e - std::sys_common::backtrace::print::hb982056c6f29541c
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x559a6e65df13 - std::panicking::default_hook::{{closure}}::h11f92f82c62fbd68
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:272:22
  10:     0x559a6e65eeca - std::panicking::default_hook::hb8810fe276772c66
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:292:9
  11:     0x559a6e65eeca - std::panicking::rust_panic_with_hook::hd2f0efd2fec86cb0
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:731:13
  12:     0x559a6e65ea0c - std::panicking::begin_panic_handler::{{closure}}::h3651b7fc4f61d784
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:609:13
  13:     0x559a6e65e966 - std::sys_common::backtrace::__rust_end_short_backtrace::hbc468e4b98c7ae04
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x559a6e65e951 - rust_begin_unwind
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
  15:     0x559a6dde3324 - core::panicking::panic_fmt::h979245e2fdb2fabd
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
  16:     0x559a6e5d8635 - slint_lsp::language::completion::add_components_to_import::h155f118057cfebae
  17:     0x559a6e5d2bdf - slint_lsp::language::completion::completion_at::h6beab7d03c9d55e0
  18:     0x559a6e543b77 - slint_lsp::language::RequestHandler::register::{{closure}}::{{closure}}::ha637f5e9e21cf141
  19:     0x559a6e567e24 - slint_lsp::<impl slint_lsp::language::RequestHandler>::handle_request::{{closure}}::hbc8826e47fb517f2
  20:     0x559a6e5628c8 - slint_lsp::run_lsp_server::h9f5376b06d91470c
  21:     0x559a6de38bf7 - std::sys_common::backtrace::__rust_begin_short_backtrace::hfd5f73cbff0a5edd
  22:     0x559a6e57878d - core::ops::function::FnOnce::call_once{{vtable.shim}}::hd61f00c9dcd67f08
  23:     0x559a6e6600b5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfa37c25e0ad051b0
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2007:9
  24:     0x559a6e6600b5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9486bed8ab2e65ad
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2007:9
  25:     0x559a6e6600b5 - std::sys::unix::thread::Thread::new::thread_start::hd28b46dbf5673d17
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys/unix/thread.rs:108:17
  26:     0x7fd7986fe044 - <unknown>
  27:     0x7fd79877e61c - <unknown>
  28:                0x0 - <unknown>
[Info  - 10:24:50 PM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
thread 'LanguageServer' panicked at tools/lsp/language/completion.rs:637:42:
Cannot parse URL for file '"src/bin/test1/ui/network.slint"'
stack backtrace:
   0:     0x55d94c806c5f - std::backtrace_rs::backtrace::libunwind::trace::h67a838aed1f4d6ec
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55d94c806c5f - std::backtrace_rs::backtrace::trace_unsynchronized::h1d1786bb1962baf8
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55d94c806c5f - std::sys_common::backtrace::_print_fmt::h5a0b1f807a002d23
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55d94c806c5f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf84ab6ad0b91784c
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55d94c071d3c - core::fmt::rt::Argument::fmt::h28f463bd1fdabed5
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/rt.rs:138:9
   5:     0x55d94c071d3c - core::fmt::write::ha37c23b175e921b3
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/mod.rs:1114:21
   6:     0x55d94c7ccf5d - std::io::Write::write_fmt::haa1b000741bcbbe1
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/io/mod.rs:1763:15
   7:     0x55d94c80832e - std::sys_common::backtrace::_print::h1ff1030b04dfb157
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55d94c80832e - std::sys_common::backtrace::print::hb982056c6f29541c
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55d94c807f13 - std::panicking::default_hook::{{closure}}::h11f92f82c62fbd68
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:272:22
  10:     0x55d94c808eca - std::panicking::default_hook::hb8810fe276772c66
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:292:9
  11:     0x55d94c808eca - std::panicking::rust_panic_with_hook::hd2f0efd2fec86cb0
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:731:13
  12:     0x55d94c808a0c - std::panicking::begin_panic_handler::{{closure}}::h3651b7fc4f61d784
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:609:13
  13:     0x55d94c808966 - std::sys_common::backtrace::__rust_end_short_backtrace::hbc468e4b98c7ae04
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x55d94c808951 - rust_begin_unwind
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
  15:     0x55d94bf8d324 - core::panicking::panic_fmt::h979245e2fdb2fabd
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
  16:     0x55d94c782635 - slint_lsp::language::completion::add_components_to_import::h155f118057cfebae
  17:     0x55d94c77cbdf - slint_lsp::language::completion::completion_at::h6beab7d03c9d55e0
  18:     0x55d94c6edb77 - slint_lsp::language::RequestHandler::register::{{closure}}::{{closure}}::ha637f5e9e21cf141
  19:     0x55d94c711e24 - slint_lsp::<impl slint_lsp::language::RequestHandler>::handle_request::{{closure}}::hbc8826e47fb517f2
  20:     0x55d94c70c8c8 - slint_lsp::run_lsp_server::h9f5376b06d91470c
  21:     0x55d94bfe2bf7 - std::sys_common::backtrace::__rust_begin_short_backtrace::hfd5f73cbff0a5edd
  22:     0x55d94c72278d - core::ops::function::FnOnce::call_once{{vtable.shim}}::hd61f00c9dcd67f08
  23:     0x55d94c80a0b5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfa37c25e0ad051b0
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2007:9
  24:     0x55d94c80a0b5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9486bed8ab2e65ad
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2007:9
  25:     0x55d94c80a0b5 - std::sys::unix::thread::Thread::new::thread_start::hd28b46dbf5673d17
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys/unix/thread.rs:108:17
  26:     0x7fb042fc9044 - <unknown>
  27:     0x7fb04304961c - <unknown>
  28:                0x0 - <unknown>
[Info  - 10:24:50 PM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
```
Any idea what is going wrong here?

**Comment by ogoffart** [comment] 2024-01-15 17:06
`src/bin/test1/ui/network.slint` is definitively a path, why can it not be parsed?  Maybe a `\` vs `/` thing if this is on windows. On what platform are you?
Maybe this code path expect some canonical path and for some reason this was not canonicalized?

**Comment by eugenwintersberger** [comment] 2024-01-15 20:00
I am working on Linux. I will try to setup a small repository with an example to reproduce the bug.

**Comment by eugenwintersberger** [comment] 2024-01-15 20:15
Here you go: https://github.com/eugenwintersberger/slint-lsp-issues
Any editing operation in the Slint file will cause the language server to crash with the following error message

```
thread 'LanguageServer' panicked at tools/lsp/language/completion.rs:637:42:
Cannot parse URL for file '"src/ui/ui.slint"'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 9:07:56 PM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
thread 'LanguageServer' panicked at tools/lsp/language/completion.rs:637:42:
Cannot parse URL for file '"src/ui/ui.slint"'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 9:08:18 PM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
thread 'LanguageServer' panicked at tools/lsp/language/completion.rs:637:42:
Cannot parse URL for file '"src/ui/ui.slint"'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 9:09:29 PM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
thread 'LanguageServer' panicked at tools/lsp/language/completion.rs:637:42:
Cannot parse URL for file '"src/ui/ui.slint"'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 9:09:29 PM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
thread 'LanguageServer' panicked at tools/lsp/language/completion.rs:637:42:
Cannot parse URL for file '"src/ui/ui.slint"'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Error - 9:10:22 PM] The Slint LSP server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
[Error - 9:10:23 PM] Delivering pending changes failed
TypeError: this.task is not a function
	at /home/eugen/.vscode/extensions/slint.slint-1.3.2/node_modules/vscode-languageclient/lib/common/utils/async.js:28:35
```

**Comment by eugenwintersberger** [comment] 2024-01-17 07:45
Hi guys. I tried the nightly extension yesterday and the problem seems to be gone. I will give this a try for some time and report back to you if the problem appears again.

**Comment by ogoffart** [comment] 2024-01-17 09:58
btw, i couldn't reproduce your bug even with the released version.
I strongly suspect that this has to do with what files are in the cache.
so you may want to restart the slint lsp server between edits in order to minimize.
But it is also possible that this was fixed in nightly (if i'd have to guess, it was maybe fixed by https://github.com/slint-ui/slint/pull/3134 )

**Comment by ogoffart** [comment] 2024-01-19 11:15
Closing for now since you think it is fixed. Please reopen if the problem persist.

**Closed by ogoffart** 2024-01-19 11:15 UTC
Labels: a:lsp
