### ISSUE TITLE
Qt backend: Application crashes when closing a `PopupWindow` with a right click

### ISSUE THREAD

**Issue by nununoisy** [slint-ui/slint#4129] opened 2023-12-09 17:16 UTC
**Steps to reproduce:**
- Use the Qt backend (I can't reproduce this on the winit backend).
- Open a `PopupWindow` with the property `close-on-click` set to `true`.
- Right-click anywhere on the application window.

**Expected outcome:** The `PopupWindow` should close, matching the behavior of left- or middle-clicking on the application window.

**Actual outcome:** The application crashes with a return of `0xc0000005 (STATUS_ACCESS_VIOLATION)`.

You can try reproducing the bug in [GBPresenter v0.6.0][1] - an affected `PopupWindow` can be opened by clicking on the info button in the top right corner. I can also reproduce the bug within `slint-viewer` when viewing `main.slint`, so I'm confident that the bug is in Slint.

I am using:
- Windows 10 22H2 (I have recieved reports from people using Windows 11 22H2 and 23H2 also)
- Rust 1.73.0 stable
- Qt 6.5.1
- Slint 1.3.2

[1]: https://github.com/nununoisy/gb-presenter-rs/releases/tag/v0.6.0

**Comment by ogoffart** [comment] 2023-12-12 07:55
Thanks a lot for the bug report.

I couldn't reproduce the issue on Linux. And I don't have a Qt setup on my windows VM at the moment.
Do you have a backtrace by any chance?
As I workaround, i recommend not using the Qt backend on windows. 

(Opening the main.slint from gbpresenter with the slint-viewer, i noticed another panic fixed in https://github.com/slint-ui/slint/pull/4140)

**Comment by tronical** [comment] 2023-12-12 08:20
I've tried to reproduce this but I can't seem to make it crash. This is with current slint, Qt 6.5.1 (MSVC). Here's a clip. Am I doing the wrong steps somehow?

https://github.com/slint-ui/slint/assets/1486/6c9d4e74-cc02-4bf2-9da1-7ab94f119c80

**Comment by ogoffart** [comment] 2023-12-13 08:36
Thanks for the detailed debug! This is very useful.
This is strange that we can't reproduce it for us.
But you might be right that we should use deleteLater to destroy.  We can probably do something like that: https://stackoverflow.com/a/41408511

**Closed** 2023-12-18 08:03 UTC
Labels: bug, a:backend-qt
