### ISSUE TITLE
DatePickerPopup

### ISSUE THREAD

**Issue by Carson-yy** [slint-ui/slint#6147] opened 2024-09-15 13:59 UTC
After setting the `width` and `height` properties for `DatePickerPopup`, it cannot be reduced any smaller after reaching a certain size. How can I make it smaller?

**Comment by ogoffart** [comment] 2024-09-24 09:03
Closing as a duplicate of #6000 but thanks anyway for filing an issue.

**Closed by ogoffart** 2024-09-24 09:03 UTC
