### ISSUE TITLE
Irreproducible panic in Pico Printer Demo

### ISSUE THREAD

**Issue by barafael** [slint-ui/slint#2512] opened 2023-04-08 16:34 UTC
Hi :)

I just built and flashed the printer demo for Pi Pico. The main homepage appeared, nice. Then I clicked the "Copy" button on the homepage, and got a nice blue screen with a panic message on it. It was complaining about `calling .unwrap() on a None value` on this line:

https://github.com/servo/euclid/blob/master/src/size.rs#L323

Then I tried it in the simulator. There was no `panic` there. After some playing around to see if I could find it, I flashed a completely clean build again and there is no more panic, I simply see the "Copy" and "Scan" sub pages when I click on their buttons.

Later I tried a different Pico, and there, the same panic happened IMMEDIATELY on boot. Reflashed another clean build, then it was fine.

I tried completely clearing the flash before and even installing micropython before flashing the printer demo, but could not reproduce the issue, also not on a third or fourth pico.

Sorry for the chaotic sequence of events I described here. The issue seems elusive.

I promise I indeed saw the blue screen with a panic message and a blinking LED!

All of this happened on master branch as of fd3f974d7e0decabbfa8a1abc36a55dc271f2aaa.
I am flashing with `elf2uf2-rs` like recommended in the readme.

If there is anything you want me to try, please let me know.

Otherwise, this is great! All the best,
Rafael

**Comment by ogoffart** [comment] 2023-04-11 11:06
What exact command line do you use to do the build?

What you can do is try to use a probe and run with probe-run and the panic-probe feature of the mcu-board-support crate, then one should get a backtrace

**Comment by ogoffart** [comment] 2023-05-08 10:13
Since we can't reproduce this, i'm afraid i'll just have to close this bug.
Thanks anyway for taking the time to fill a bug report.

**Closed by ogoffart** 2023-05-08 10:13 UTC

**Comment by barafael** [comment] 2023-05-08 12:31
For future reference, I tried to reproduce with a probe attached, but gained no further info.
