### ISSUE TITLE
The Slint Language Server crashed: `Recursion detected`

### ISSUE THREAD

**Issue by NNKTV28** [slint-ui/slint#4342] opened 2024-01-15 08:44 UTC
Im using VsCode in windows 10

i have a slint file and i just run the command for slint preview

no idea the console output just gives me this 
´´´
thread 'main' panicked at internal\core\properties.rs:486:9:
Recursion detected
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 9:41:30 AM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
´´´

**Comment by ogoffart** [comment] 2024-01-15 17:26
Could be the same as https://github.com/slint-ui/slint/issues/4081 or https://github.com/slint-ui/slint/issues/3989 or both.
#3989 is fixed in the nightly extension already.  Perhaps you can try the nightly extension and tell us if the problem is still there.

**Comment by ogoffart** [comment] 2024-01-19 11:16
Should be fixed in the nightly extension.
Please re-open if the problem persist.

**Closed by ogoffart** 2024-01-19 11:16 UTC
Labels: a:live preview
