### ISSUE TITLE
QTBackend Preferred Window Sizing Does not Match Winit

### ISSUE THREAD

**Issue by bryce-happel-walton** [slint-ui/slint#6838] opened 2024-11-20 05:57 UTC
### Bug Description

`slint/backend-qt` will prefer to keep the window within the monitor's bounds rather than using the `preferred-size`.
`slint/backend-winit` will use the `preferred-size` (this is the preferred functionality)

The live preview uses the `preferred-size`

This does not occur with QML/Qt native, so not sure what's happening here.

### Reproducible Code (if applicable)

```slint
export component AppWindow inherits Window {
    preferred-width: 1920px;
    preferred-height: 720px;
}
```

### Environment Details

- Slint Version: 1.8.0 & development snapshot (1.9.0)
- Platform/OS: Apple M1 (Fedora Asahi Remix 40) KDE Plasma 6.2.3 Frameworks 6.8.0
- Kernel: 6.11.8-400.asahi.fc40.aarch64+16k (64-bit)
- System Qt Version: 6.7.2
- Programming Language: Rust
- Backend/Renderer: FemtoVG

### Product Impact

Not a huge deal, but definitely inconvenient.

**Comment by tronical** [comment] 2024-11-20 09:35
That's bizarre :). The handling of the preferred size should be in the winit backend, independent from the renderers. Am I correct in assuming that you're using Wayland? How exactly do you select the renderers? Do you have a small example for us to reproduce maybe (I have the feeling this is a setup issue).

**Comment by bryce-happel-walton** [comment] 2024-11-21 01:24
> That's bizarre :). The handling of the preferred size should be in the winit backend, independent from the renderers. Am I correct in assuming that you're using Wayland? How exactly do you select the renderers? Do you have a small example for us to reproduce maybe (I have the feeling this is a setup issue).

Yes, after testing I found this to be a backend issue with the Qt backend rather than the renderer. I have updated the issue. I am using Wayland.

To reproduce just make a window and set the preferred size to be greater than your monitor's size and the window will be resized to be within bounds rather than respecting the preferred size.

**Comment by bryce-happel-walton** [comment] 2024-11-21 01:27
@ogoffart I've updated the issue. It is not a femtovg bug.

**Comment by ogoffart** [comment] 2024-11-21 09:12
I believe this might be a duplicate of https://github.com/slint-ui/slint/issues/3847

Are you able to run this Qt program and report what is the size of the window?
```cpp
#include <QtWidgets>
struct W : QWidget {
    QSize sizeHint() const override { return QSize{1920, 720}; }
};
int main(int argc, char**argv) {
    QApplication app(argc, argv);
    W w;
    w.show();
    qDebug() << w.size();
    return app.exec();
}
```

For me, it looks like Qt doesn't respect the sizeHint (Qt6.8.0 plasma 6.2.3 x11)

**Comment by ogoffart** [comment] 2024-12-11 12:52
I'm going to assume this is the same as #3847 and close it as duplicate.
Thanks anyway for filing an issue.

**Closed** 2024-12-11 12:52 UTC
Labels: bug, a:backend-qt, need triaging
