### ISSUE TITLE
Overlapping ComboBox is cut off

### ISSUE THREAD

**Issue by d3im** [slint-ui/slint#3927] opened 2023-11-14 06:53 UTC
Slint version 1.2.2 and 1.3.0 with Rust.
Opening ComboBox cuts out overlapping entries.
Is there any workaround? Illustration of situation:
![overlap](https://github.com/slint-ui/slint/assets/17542229/8925f5f7-2dba-400a-9ada-cc498f821256)

**Comment by ogoffart** [comment] 2023-11-14 08:22
Thanks for reporting the issue.

This is the same as https://github.com/slint-ui/slint/issues/2375
The issue is that the winit crate don't support popups.

In the meantime the workaround is to use the qt backend.

Closing as duplicate but thanks for the report anyway.

**Closed by ogoffart** 2023-11-14 08:22 UTC
