### ISSUE TITLE
Conditional elements break layout

### ISSUE THREAD

**Issue by metalinspired** [slint-ui/slint#3317] opened 2023-08-21 16:17 UTC
If this is intended behaviour it should be documented.
The button does not render properly in following snippet.

```
import { Button, VerticalBox , HorizontalBox} from "std-widgets.slint";
export component Demo {
    HorizontalBox {
        Rectangle {
            if (true) : VerticalLayout {
                Button {
                    height: 50px;
                    width: 50px;
                    text: "OK!";
                } 
            }
        }
    }
}
```

If you remove `if (true) : ` it will render fine.

Kubuntu 23.04 
Slint 1.1

**Comment by ogoffart** [comment] 2023-08-21 18:59
Thanks for reporting.
This is already known https://github.com/slint-ui/slint/issues/407#issuecomment-897681718  but sadly not trivial to fix

**Comment by ogoffart** [comment] 2024-01-15 09:44
Duplicate of #407

**Closed by ogoffart** 2024-01-15 09:44 UTC
Labels: duplicate
