### ISSUE TITLE
Add methods to obtain window dimensions.

### ISSUE THREAD

**Issue by vgarleanu** [slint-ui/slint#939] opened 2022-02-11 20:19 UTC
Slint currently lacks any methods of obtaining the width and height of the active window directly. These methods would be useful when working with OpenGL underlays.

It would be useful if these methods were added in.

**Comment by tronical** [comment] 2022-02-11 20:33
Olivier had a very nice idea regarding that:

It makes sense to distinguish between the size in device independent (logical) pixels and the device (physical) pixels.

His idea is to use euclid: A size getter can return a `euclid::Size2D` that is tagged with a `PhysicalLength` or `LogicalLength` and we can also provide a `euclid::Scale` on the Window to allow for conversion.

In C++ we can could perhaps have two getter functions :)

**Comment by tronical** [comment] 2022-02-28 07:57
I realise that this is a duplicate of #323 . I added a reference to this ticket there to take into account the physical vs. logical idea.

**Closed by tronical** 2022-02-28 07:57 UTC
Labels: enhancement
