### ISSUE TITLE
Conditional code and identifier

### ISSUE THREAD

**Issue by trobanga** [slint-ui/slint#4647] opened 2024-02-20 18:12 UTC
Starting from the example [Conditional Element](https://slint.dev/releases/1.4.1/docs/slint/src/language/syntax/conditions), I would like to access `foo`, e.g.

```
export component Example inherits Window {
    preferred-width: 50px;
    preferred-height: 50px;
    if area.pressed : foo := Rectangle { background: blue; }
    if !area.pressed : Rectangle { background: red; }
    area := TouchArea {
        clicked => {
            foo.height = 100px;
        }
    }
}
```

but it fails with `error: Cannot access id 'foo'`.

My current workaround is to set the inactive component's height to 0 but it would be nice if the access would work.

I guess the problem is that the component only exists if area.pressed is true.

So maybe the access should be like
```
if foo.pressed {
    foo.height = 100px;
}
```

**Comment by asuper0** [comment] 2024-02-22 01:37
I add a identifier to the `!area.pressed` one, and also has error.
Suggest to use [`States`](https://slint.dev/releases/1.4.1/docs/slint/src/language/syntax/states) instead of `Conditional Element`

**Comment by trobanga** [comment] 2024-02-22 07:44
As far as I understand, `States` only work for properties. 
In my use case I have a `TextEdit` that I want to set the focus to, i.e. calling `foo.focus()`.

**Comment by ogoffart** [comment] 2024-09-09 09:30
Duplicate of https://github.com/slint-ui/slint/issues/4891

**Closed by ogoffart** 2024-09-09 09:30 UTC
