### ISSUE TITLE
hi, I use linux and rust as backend. I want to open a filedialog to select a file in filesystem. slint provides any function to do this?

### ISSUE THREAD

**Issue by Heng30** [slint-ui/slint#2583] opened 2023-04-19 01:52 UTC

**Comment by Vadoola** [comment] 2023-04-19 04:45
I remember seeing a Discussion that answered this questions a few months ago: https://github.com/slint-ui/slint/discussions/1959

**Comment by ogoffart** [comment] 2023-04-19 05:10
Hi,

Thanks @Vadoola for replying.
File dialog can indeed be done using the rfd crate.

Closing this issue as duplicate of #1959

**Closed by ogoffart** 2023-04-19 05:10 UTC
