### ISSUE TITLE
Wayland warnings on shutdown

### ISSUE THREAD

**Issue by Be-ing** [slint-ui/slint#2728] opened 2023-05-15 00:11 UTC
I've reproduced this on two applications now, Moire and the [slint-cpp-template](https://github.com/slint-ui/slint-cpp-template/issues/13).

```
warning: queue 0x7f8a0c000ca0 destroyed while proxies still attached:
  zwp_primary_selection_offer_v1@4278190081 still attached
  wl_data_offer@4278190080 still attached
  zwp_primary_selection_device_v1@26 still attached
  zwp_primary_selection_device_manager_v1@22 still attached
  wl_data_device@25 still attached
  wl_data_device_manager@24 still attached
  wl_seat@23 still attached
  wl_registry@21 still attached
warning: queue 0x55ee349f59c0 destroyed while proxies still attached:
  wl_buffer@50 still attached
  wl_buffer@49 still attached
  wl_shm_pool@48 still attached
  wl_buffer@42 still attached
  wl_shm_pool@47 still attached
  xdg_wm_base@35 still attached
  wl_output@15 still attached
  zwp_text_input_manager_v3@14 still attached
  xdg_activation_v1@13 still attached
  wl_subcompositor@12 still attached
  zwp_relative_pointer_manager_v1@11 still attached
  zwp_pointer_constraints_v1@10 still attached
  wl_seat@9 still attached
  wl_shm@8 still attached
  wp_fractional_scale_manager_v1@7 still attached
  wp_viewporter@6 still attached
  zxdg_decoration_manager_v1@5 still attached
  wl_compositor@4 still attached
  wl_registry@2 still attached
```

**Comment by Be-ing** [comment] 2023-05-15 00:14
I can reproduce this on KDE, GNOME, and Weston.

**Comment by Berrysoft** [comment] 2023-05-15 07:00
I can reproduce this on wslg.

**Comment by ogoffart** [comment] 2023-05-17 09:11
Could you attach a debugger and try to get a backtrace to find out what emits these warings?

**Comment by tronical** [comment] 2023-05-17 14:41
I can't reproduce this :(. I'm using debug builds, against Weston. I see this neither with slint-cpp-template nor with the rust builds of say the gallery. I'm using libwayland 1.21.

**Comment by ogoffart** [comment] 2023-05-19 07:49
I can't reproduce this. I tried both the winit (femtovg) backend and the Qt(6) backend with gnome and plasma wayland.  No warning appears.  (I only tried the slint-cpp-example)

My versions: Slint 1.0.2, GNOME 44.0, Plasma 5.27.4

**Comment by ultimaweapon** [comment] 2023-06-28 10:59
I can reproduce this on GNOME running on latest Arch Linux with `SLINT_NO_QT=1` using the following code:

```rs
use slint::slint;

fn main() {
    MainWindow::new().unwrap().run().unwrap();
}

slint! {
    export component MainWindow inherits Window {
        Text {
            text: "hello world";
            color: green;
        }
    }
}
```

My Cargo.toml:

```toml
[package]
name = "slinttest"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = "1.1"
```

My logs:

```
[~/Workspace/personal/slinttest:0]$ SLINT_NO_QT=1 cargo run
   Compiling i-slint-backend-qt v1.1.0
   Compiling i-slint-backend-selector v1.1.0
   Compiling slint v1.1.0
   Compiling slinttest v0.1.0 (/home/ultimaweapon/Workspace/personal/slinttest)
    Finished dev [unoptimized + debuginfo] target(s) in 5.64s
     Running `target/debug/slinttest`
warning: queue 0x7f021c000ca0 destroyed while proxies still attached:
  zwp_primary_selection_offer_v1@4278190083 still attached
  wl_data_offer@4278190082 still attached
  zwp_primary_selection_device_v1@25 still attached
  zwp_primary_selection_device_manager_v1@21 still attached
  wl_data_device@24 still attached
  wl_seat@23 still attached
  wl_data_device_manager@22 still attached
  wl_registry@20 still attached
warning: queue 0x55bb3bdb8b80 destroyed while proxies still attached:
  wl_buffer@51 still attached
  wl_buffer@65 still attached
  wl_buffer@63 still attached
  wl_buffer@59 still attached
  wl_buffer@56 still attached
  wl_shm_pool@61 still attached
  wl_buffer@62 still attached
  wl_shm_pool@55 still attached
  wl_subsurface@45 still attached
  wl_surface@44 still attached
  wl_subsurface@43 still attached
  wl_surface@42 still attached
  wl_subsurface@41 still attached
  wl_surface@40 still attached
  wl_subsurface@39 still attached
  wl_surface@38 still attached
  wl_subsurface@37 still attached
  wl_surface@36 still attached
  xdg_wm_base@34 still attached
  wl_output@15 still attached
  wl_output@14 still attached
  xdg_activation_v1@13 still attached
  zwp_text_input_manager_v3@12 still attached
  zwp_pointer_constraints_v1@11 still attached
  zwp_relative_pointer_manager_v1@10 still attached
  wl_seat@9 still attached
  wp_fractional_scale_manager_v1@8 still attached
  wp_viewporter@7 still attached
  wl_subcompositor@6 still attached
  wl_shm@5 still attached
  wl_compositor@4 still attached
  wl_registry@2 still attached
[~/Workspace/personal/slinttest:0]$
```

**Comment by ogoffart** [comment] 2023-09-07 10:31
These warning doesn't come from us, but from winit or GL driver.
https://github.com/rust-windowing/winit/issues/2761

Not much we can do about it. So closing this issue as an "upstream" issue.

**Closed** 2023-09-07 10:31 UTC
Labels: bug, a:platform-linux, a:backend-winit
