### ISSUE TITLE
Weird and ugly font on Ubuntu 20.04/VirtualBox

### ISSUE THREAD

**Issue by douglaz** [slint-ui/slint#972] opened 2022-02-20 18:05 UTC
Just running cargo run --bin gallery:

![image](https://user-images.githubusercontent.com/163706/154857090-66f59559-0eae-433b-9546-028b7271059d.png)

(using the GL backend, AFAIK)

A similar setup running outside a VM works fine.

**Comment by tronical** [comment] 2022-02-20 21:41
Hmm I’ve see this before but I can’t recall when/how. Is this a Linux vm setup that I can reproduce? (Is it say a stock $foo distro install?

**Comment by tronical** [comment] 2022-02-20 21:43
Visually this looks like some kind of winding problem with the glyph paths - at least that’s what the screenshot reminds me of :)

**Comment by tronical** [comment] 2022-02-20 21:45
The slider knob looks similarly “mis-rendered”, when it should be filled. Hmmmmmm

**Comment by tronical** [comment] 2022-02-20 21:45
What resolution are you using? Do you know if this is with Wayland? (I’m assuming this is Slint 0.2.0?)

**Comment by douglaz** [comment] 2022-02-21 04:20
> What resolution are you using? Do you know if this is with Wayland? (I’m assuming this is Slint 0.2.0?)

It's the default xorg that comes on Ubuntu 20.04, master version of slint. I tried with different resolutions (because it's a vm) and all give the same result.

But I've found one way to "fix" it: just disable 3d acceleration on virtual box settings :man_shrugging:

**Comment by tronical** [comment] 2022-02-21 10:00
Oh. So perhaps that is a bug in the virtual box GL driver. Not sure if there's anything that we can do about it :-/. I'm glad that you've found a workaround though!

**Comment by ogoffart** [comment] 2022-11-29 11:45
Closing this since there is nothing we can do about it

**Closed by ogoffart** 2022-11-29 11:45 UTC
Labels: font
