### ISSUE TITLE
Can't initialise a struct which includes an array of other structs in `.slint`

### ISSUE THREAD

**Issue by Zajozor** [slint-ui/slint#944] opened 2022-02-13 15:08 UTC
Maybe i'm just using the wrong syntax, or something, but if I have two structs, and one contains an array of the other, i'm having trouble initialising it's values in the slint language.
Example:
```
struct inner := { innerprop: float }
struct outerSingle := { outerprop: inner }  // This contains just one inner, and works fine
struct outerArray := { outerprop: [inner] }  // This contains an array of inner's and does not work

Some := Window {
  property<inner> prop2: { // This works fine
    innerprop: 5,
  };

  property<outerSingle> prop1: { // This works fine too
    outerprop: {
      innerprop:6,
    },
  };

  // This throws error - `Cannot convert { outerprop: [{ innerprop: float,}],} to outerArray`
  property<outerArray> prop3: {
    outerprop: [{
      innerprop:7,
    }],
  };
}
```

I would expect prop3 to understand that `{ outerprop: [{ innerprop: float,}],}` is in fact `outerArray`.
Is there some other syntax for this or a workaround?

( the value is still settable from Rust code, eg.:
```
 window.set_prop3(outerArray {
        outerprop: VecModel::from_slice(&[inner { innerprop: 3.0 }]),
    });
```
but i'd like to see something in the slint preview window)

Thanks!

**Comment by ogoffart** [comment] 2022-02-13 16:34
Looks like a bug in the type conversion rules

**Comment by ogoffart** [comment] 2022-02-13 17:20
I think the problem is that Expression::maybe_conver_to  does not accept to convert struct of array.

There is some code that handle array conversion in 
https://github.com/slint-ui/slint/blob/master/internal/compiler/expression_tree.rs#L867

But this code may not be reached when the array is nested in a struct.

**Comment by ogoffart** [comment] 2022-02-13 17:23
The thing is that in general, we can't cast an expression of type `[foo]` to type `[bar]` even if foo can be converted to bar. because model needs to have exactly the same type.  But with raw array, we should be able to do the conversion

**Comment by robbym** [comment] 2022-02-21 07:34
Just ran into this issue as well. Is there a proposed fix for this? Is there a syntax for explicit conversion?

**Comment by Zajozor** [comment] 2022-02-21 07:39
I was considering looking into it - and I think i understand where to add the tests or the implementation,
but indeed i am not sure about what to implement 😅 

example idea:
- add an additional method `maybe_same_type` which is essentially a `maybe_can_convert_to` but checks for exact type equality not just convertibility. (and in the case of structs it does so by comparing the members)
- in the appropriate branch of `maybe_same_type` with `[foo]` and `[bar]` we would run `maybe_same_type` and allow `convet_to` only if `foo` and `bar` are exactly the same type

Would an approach like this possibly solve the problem? (I am honestly not sure, I don't have the bigger picture built yet)

**Comment by ogoffart** [comment] 2022-02-21 09:51
I think all you need to do is to fix `maybe_convert_to` to special-case the Struct to recursively call maybe_convert_to with  all its fields.  That can be done similarily to the special case for array: https://github.com/slint-ui/slint/blob/136f2686b4e33241da8e7ab97bf27712a8d5bf56/internal/compiler/expression_tree.rs#L977

**Closed** 2022-03-28 12:41 UTC
Labels: bug, compiler
