### ISSUE TITLE
Language server crashed

### ISSUE THREAD

**Issue by rscarson** [slint-ui/slint#6300] opened 2024-09-24 19:34 UTC
related to this:
```
VerticalBox {
                    property <int> rows: root.frequencies.length / 8;
                    for i in rows: HorizontalBox {
                        padding: 0;

                        for j in 8: IconButton {
                            small: true;
                            text: root.frequencies[i * 8 + j];
                            icon: @image-url("assets/icons/minus-circle.svg");
                        }
                    }
                }
```

Crashed on preview each time
Removed it, crash vanished. Put it back... Still gone

```
thread 'main' panicked at internal\renderers\skia\itemrenderer.rs:236:17:
attempt to divide by zero
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 3:32:40 PM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug. Please open an issue on https://github.com/slint-ui/slint/issues
Failed Direct3D call. Error: 0x887a0005
Failed Direct3D call. Error: 0x80070057
Failed Direct3D call. Error: 0x80070057
Failed Direct3D call. Error: 0x80070057
Failed Direct3D call. Error: 0x80070057
thread 'main' panicked at tools\lsp\preview\native.rs:122:40:
called `Result::unwrap()` on an `Err` value: Other("Error presenting d3d swap chain: 887a0005")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 3:32:57 PM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug. Please open an issue on https://github.com/slint-ui/slint/issues
```

**Comment by tronical** [comment] 2024-09-24 20:06
Would it be possible to attach the svg that causes this? (Thanks for the report btw :)

**Comment by tronical** [comment] 2024-09-25 10:42
Duplicate of #6280

**Closed by tronical** 2024-09-25 10:42 UTC
