### ISSUE TITLE
Custom draggable region for frameless window

### ISSUE THREAD

**Issue by wspl** [slint-ui/slint#2695] opened 2023-05-05 05:16 UTC
Perhaps we can add a builtin element to allow users to add draggable areas in the UI. This is usually used to enable users to drag frameless windows on custom title bars.

In Electron, we usually use a piece of CSS: `-webkit-app-region: drag` ([documentation](https://www.electronjs.org/pt/docs/latest/api/frameless-window#draggable-region)) to set a DOM element as a draggable area. Electron will obtain the position of this DOM element after layout and call the system API to set this area as a draggable area.

**Comment by ogoffart** [comment] 2023-05-05 07:08
Closing as duplicate of https://github.com/slint-ui/slint/issues/613

**Closed by ogoffart** 2023-05-05 07:08 UTC

**Comment by chonwhite** [comment] 2023-10-25 05:20
Is the feature implemented yet? Any reference on how to implement it manually?

**Comment by ogoffart** [comment] 2023-10-25 07:41
@chonwhite  while this hasn't been implemented yet, there is some valuable discussion in https://github.com/slint-ui/slint/discussions/3355 on how to do implement it manually
