### ISSUE TITLE
There is garbled text in Chinese input.中文乱码不知道什么时候能解决一下

### ISSUE THREAD

**Issue by allenlu2008** [slint-ui/slint#3427] opened 2023-09-07 11:15 UTC
There is garbled text in Chinese input.
中文输入的乱码，不知道什么时候能解决一下

**Comment by tronical** [comment] 2023-09-07 11:59
Hi! Thanks for reporting this. Am I correct in assuming that you're see this in the WASM demos that are running in the web browser?

If yes, then this is likely a duplicate of #2563.

**Comment by allenlu2008** [comment] 2023-09-07 12:18
When I input Chinese on the official wasm demo, the characters were garbled, but after updating my local project, the Chinese became normal.

**Comment by tronical** [comment] 2023-09-07 12:41
Thanks for checking! Then this is indeed a duplicate of #2563

**Closed by tronical** 2023-09-07 12:41 UTC
Labels: bug, needs info
