### ISSUE TITLE
Detection of focus lose 

### ISSUE THREAD

**Issue by serpack** [slint-ui/slint#4462] opened 2024-01-27 22:41 UTC
Is there a "build-in" way a component (like LineEdit) can detect it has lost the focus?

**Comment by tronical** [comment] 2024-01-28 08:45
#3650 added support for focus-changed-event: https://slint.dev/snapshots/master/docs/slint/src/language/builtins/elements#callbacks

This will be in the upcoming 1.4 release.

**Comment by tronical** [comment] 2024-01-28 08:46
Duplicate of #1236

**Closed by tronical** 2024-01-28 08:46 UTC

**Comment by Enyium** [comment] 2024-08-24 18:18
@tronical: The question was about components like `LineEdit`s etc., though. When you wrap a `LineEdit` in a `FocusScope`, this not only is undesirable boilerplate, but also gives you two focusable elements. [SlintPad example](https://slintpad.com/?snippet=import+%7B+Button%2C+VerticalBox%2C+LineEdit+%7D+from+%22std-widgets.slint%22%3B%0Aexport+component+Demo+%7B%0A++++VerticalBox+%7B%0A++++++++alignment%3A+start%3B%0A%0A++++++++FocusScope+%7B%0A++++++++++++btn1+%3A%3D+Button+%7B+text%3A+%22___%22%3B+%7D%0A%0A++++++++++++focus-changed-event+%3D%3E+%7B%0A++++++++++++++++if+%21self.has-focus+%7B%0A++++++++++++++++++++btn1.text+%3D+btn1.text+%3D%3D+%22abc%22+%3F+%22def%22+%3A+%22abc%22%3B%0A++++++++++++++++%7D%0A++++++++++++%7D%0A++++++++%7D%0A%0A++++++++FocusScope+%7B%0A++++++++++++le+%3A%3D+LineEdit+%7B+text%3A+%22___%22%3B+%7D%0A%0A++++++++++++focus-changed-event+%3D%3E+%7B%0A++++++++++++++++if+%21self.has-focus+%7B%0A++++++++++++++++++++le.text+%3D+le.text+%3D%3D+%22abc%22+%3F+%22def%22+%3A+%22abc%22%3B%0A++++++++++++++++%7D%0A++++++++++++%7D%0A++++++++%7D%0A%0A++++++++FocusScope+%7B%0A++++++++++++btn2+%3A%3D+Button+%7B+text%3A+%22___%22%3B+%7D%0A%0A++++++++++++focus-changed-event+%3D%3E+%7B%0A++++++++++++++++if+%21self.has-focus+%7B%0A++++++++++++++++++++btn2.text+%3D+btn2.text+%3D%3D+%22abc%22+%3F+%22def%22+%3A+%22abc%22%3B%0A++++++++++++++++%7D%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A%7D%0A&style=native)
