### ISSUE TITLE
Conditional rendering in subcomponent destroys everything

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#6291] opened 2024-09-24 03:18 UTC
Consider [this SlintPad demo](https://slintpad.com/?snippet=import+%7B+AboutSlint%2C+Button%2C+VerticalBox+%7D+from+%22std-widgets.slint%22%3B%0A%0Acomponent+Foo+%7B%0A++++if+true+%3A+VerticalBox+%7B%0A++++++++alignment%3A+start%3B%0A++++++++%2F%2FAboutSlint+%7B%7D+%2F%2F+Makes+for+more+empty+space+at+the+top.%0A++++++++Button+%7B+text%3A+%22I+have+become+%60Text%60+only.%22%3B+%7D%0A++++++++Rectangle+%7B%0A++++++++++++width%3A+10px%3B%0A++++++++++++height%3A+10px%3B%0A++++++++++++background%3A+deeppink%3B%0A++++++++%7D%0A++++++++Text+%7B+text%3A+%22I%27m+invisible.%22%3B+%7D%0A++++++++HorizontalLayout+%7B+Button+%7B+text%3A+%22Wow%2C+normal%21%22%3B+%7D+%7D%0A++++%7D%0A%7D%0A%0Aexport+component+Demo+%7B%0A++++Foo+%7B%7D%0A%7D%0A&style=native):

```slint
import { AboutSlint, Button, VerticalBox } from "std-widgets.slint";

component Foo {
    if true : VerticalBox {
        alignment: start;
        //AboutSlint {} // Makes for more empty space at the top.
        Button { text: "I have become `Text` only."; }
        Rectangle {
            width: 10px;
            height: 10px;
            background: deeppink;
        }
        Text { text: "I'm invisible."; }
        HorizontalLayout { Button { text: "Wow, normal!"; } }
    }
}

export component Demo {
    Foo {}
}
```

When I click "Show Preview" on the upper component `Foo`, it doesn't look incorrect:

![correct](https://github.com/user-attachments/assets/7ed12363-855e-4b6a-8322-7cb28070fa1f)

But when I click "Show Preview" on the lower exported component, I get a jumbled mess:

![incorrect](https://github.com/user-attachments/assets/5dd787a5-d305-419a-a062-1a348fa743ed)

When removing `if true : `, everything is normal:

![normal](https://github.com/user-attachments/assets/e736dcb4-d3bb-421d-a7f6-4cadf22c9b10)

**Comment by ogoffart** [comment] 2024-09-26 06:24
This is a duplicate of https://github.com/slint-ui/slint/issues/407
The geometry of element is not taken for `for` or `if` so in your case, the Foo has a size of 0 and the layout constraints are not respected.
Workaround is to use a layout around the `if`:
```slint
component Foo {
  VerticalLayout {
    if true : VerticalBox {
        alignment: start;
        ...
    }
  }
}
```

**Closed by ogoffart** 2024-09-26 06:24 UTC
Labels: need triaging
