### ISSUE TITLE
Expose Window maximize API

### ISSUE THREAD

**Issue by stefnotch** [slint-ui/slint#3331] opened 2023-08-23 20:09 UTC
I'm using Slint for a fullscreen/maximized overlay. 

For that, I would love it if https://docs.rs/slint/latest/slint/struct.Window.html gained functionality equivalent to one of those two options
- https://docs.rs/winit/latest/winit/window/struct.Window.html#method.set_maximized
- https://docs.rs/winit/latest/winit/window/struct.Window.html#method.set_fullscreen

There's the somewhat related https://github.com/slint-ui/slint/issues/333 issue, but it seems rather outdated. So I figured I'd make a specific feature request instead.

My tooling
- Window 10
- Rust

**Comment by tronical** [comment] 2023-08-24 06:52
Agreed. In the meantime, what you can use as workaround is to depend on `i-slint-backend-winit` and use [`WinitWindowAccessor`](https://docs.rs/i-slint-backend-winit/latest/i_slint_backend_winit/trait.WinitWindowAccessor.html), if you're using the winit backend.

**Comment by tronical** [comment] 2023-09-04 12:50
Closing this as a duplicate of #3283

**Closed by tronical** 2023-09-04 12:50 UTC
Labels: enhancement, a:backend-winit, a:backend-qt, api

**Comment by ogoffart** [comment] 2023-09-04 13:53
@tronical Maximize is not the same as fullscreen though

On the other hand, I don't know how much of the Window API we really want to abstract/duplicate in our own API instead of just exposing winit directly

**Comment by tronical** [comment] 2023-09-04 13:56
Yes, I know it's not the same. I do think that this goes hand-in-hand implementation wise.
