### ISSUE TITLE
Please add built-in scrolling support for ComboBox widget

### ISSUE THREAD

**Issue by teknalb** [slint-ui/slint#5566] opened 2024-07-07 16:32 UTC
I have the same use case as #5304 and #2657 and currently it's only possible by making a custom component, please add this important feature to Slint.

**Comment by ogoffart** [comment] 2024-07-08 14:09
Thanks for filling an issue.
This is a duplicate of https://github.com/slint-ui/slint/issues/4727 so I'm going to close this issue. But thanks anyway for taking the time to fill an issue.

**Closed by ogoffart** 2024-07-08 14:09 UTC
Labels: a:widgets
