### ISSUE TITLE
Linux: TextEdit widget is always showing scrollbars even when empty

### ISSUE THREAD

**Issue by teknalb** [slint-ui/slint#5578] opened 2024-07-08 17:37 UTC
![scrolls](https://github.com/slint-ui/slint/assets/174643755/ddeaf32d-6d82-47da-bf77-8678d08ac13f)

**Comment by tronical** [comment] 2024-07-08 18:58
Duplicate of #3416

**Closed** 2024-10-08 15:02 UTC
Labels: bug, a:backend-qt
