### ISSUE TITLE
Missing optional properties

### ISSUE THREAD

**Issue by dorukotiv** [slint-ui/slint#6160] opened 2024-09-16 07:41 UTC
Having optional properties would be extremely useful, as currently, implementing this feature requires various workarounds.

**Comment by ogoffart** [comment] 2024-09-16 07:55
Thanks for your report.
We already had an issue for this feature: https://github.com/slint-ui/slint/issues/5164
(I just edited it to make it more clear.)
So I'm going to close this issue as duplicate of #5164, but thanks anyway for filing the issue.

**Closed by ogoffart** 2024-09-16 07:55 UTC
Labels: duplicate
