### ISSUE TITLE
Bad rectangle's border painting at 125% scaling factor

### ISSUE THREAD

**Issue by abique** [slint-ui/slint#4830] opened 2024-03-12 21:21 UTC
Steps:
1. use skia backend
2. draw a 1px rectangle border
3. run at 125% scaling, I could repro using: `SLINT_SCALE_FACTOR=1.25`
4. resize the window to make the rectangle move a bit

![Screenshot from 2024-03-12 22-16-39](https://github.com/slint-ui/slint/assets/31200/054a75aa-8612-4fa6-94cf-8e5f36338c48)
![Screenshot from 2024-03-12 22-16-28](https://github.com/slint-ui/slint/assets/31200/57ebb63b-0b15-414c-9647-a6d18a60e70f)

Versus `SLINT_SCALE_FACTOR=1`:
![Screenshot from 2024-03-12 22-19-19](https://github.com/slint-ui/slint/assets/31200/0c5a94fc-ca3d-475f-91ea-caf2379130cd)

**Comment by tronical** [comment] 2024-09-12 09:09
Duplicate of #5747

Yeah, even though #5747 is newer, I'll close this in favor of #5747 . This is a very good test-case though.

**Closed** 2024-09-12 09:10 UTC
Labels: a:renderer-skia, need triaging
