### ISSUE TITLE
Support for @1x, @2x and @3x images

### ISSUE THREAD

**Issue by NigelBreslaw** [slint-ui/slint#6435] opened 2024-10-02 14:31 UTC
Mobile platforms such as iOS and cross platform frameworks such as React Native will automatically use different images based on '*@2x.*' style file names.

So in code you would have `source: @image("images/awesome.png")`. But inside the images folder are 'awesome.png, awesome@2x.png and awesome@3x.png'. The framework then automatically uses the correct size based on its DPI. 1x being SD, 2x being standard retina, 3x being super retina. 

Most image editors allow easy export of images with these names and sizes. This leads to other questions such as if there are only @3x images could we auto resize to make @2x and @1x at build time? Or have bundling options where if you know the device to deploy to is @1x it won't bundle in the other images. Anyhoo main issue is the basic support so Slint apps don't chug on devices with SD screens and limited memory. But will still look great on devices with more pixels and power.

React Native docs https://reactnative.dev/docs/images

**Comment by ogoffart** [comment] 2024-10-02 14:50
Closing as duplicate of https://github.com/slint-ui/slint/issues/92

**Closed** 2024-10-03 04:11 UTC
Labels: duplicate
