### ISSUE TITLE
Slint image-url with https source works in SlintPad, but does not compile with cargo or wasm.

### ISSUE THREAD

**Issue by richardmcatlin** [slint-ui/slint#4132] opened 2023-12-11 03:23 UTC
This works in SlintPad, but does not compile for cargo project or webassembly.  Language: Rust.  Platform: OSX and WASM
```
export component Example inherits Window {
    in property <image> url1: @image-url("https://upload.wikimedia.org/wikipedia/commons/4/42/Berlin_potsdamer_platz.jpg");
    width: 200px;
    height: 150px;
    VerticalLayout {
        Image {
            source: url1;
            width: 200px;
            // implicit default, preserving aspect ratio:
            // height: self.width * natural_height / natural_width;
        }
    }
}
```
error: Cannot find image file https://upload.wikimedia.org/wikipedia/commons/4/42/Berlin_potsdamer_platz.jpg
--> /Users/rhettcatlin/Desktop/catlin/rust/rust_fullstack_on_aws_serverless/client_slint_puzzle/slide_puzzle.slint:112:31
|
112 | in property url1: @image-url("https://upload.wikimedia.org/wikipedia/commons/4/42/Berlin_potsdamer_platz.jpg");

**Comment by tronical** [comment] 2023-12-11 07:41
Duplicate of #3279

**Closed by tronical** 2023-12-11 07:41 UTC
