### ISSUE TITLE
Text size goes to zero when nested in a Rectangle with an if conditional

### ISSUE THREAD

**Issue by FoundationKen** [slint-ui/slint#3722] opened 2023-10-21 00:48 UTC
A `Text` component with a conditional (e.g., `if x: Text{}`) will have zero size when nested in a `Rectangle`, even if the condition is true.

If there is no conditional, then the `Text` has the expected size and the `Rectangle` matches the `Text` size.

I used a string condition below, but I also checked that a `bool` flag fails, so I expect this is for any conditional.

```
export component Demo {
    width: 400px;
    private property <string> flag;

    Rectangle {
        /* if flag == "": */ Text {  // Remove the comment on the left and the `Text` will disappear, even though the condition is true
            text: "Hello";
            font-size: 24px;
        }
    }
}
```

SlintPad repro link: https://tinyurl.com/2phdr6fu

**Comment by ogoffart** [comment] 2023-10-21 08:23
Thanks for the bug report.

The problem is that because of the `if`, the layout constraints are not propagated to the parent, meaning that the default height is 0. You can work around this problem  by explicitly setting a minimum size to the Demo component

I'm closing this issue as a duplicate of https://github.com/slint-ui/slint/issues/407 and https://github.com/slint-ui/slint/issues/3317

**Closed by ogoffart** 2023-10-21 08:23 UTC
