### ISSUE TITLE
Preview doesn't update changes in the file automatically

### ISSUE THREAD

**Issue by dorukotiv** [slint-ui/slint#6090] opened 2024-09-11 09:50 UTC
Slint preview used to update preview when the corresponding slint file is edited but not anymore. User needs to explicitly rerun the preview to see the changes. Additionally, if the parent component is used in preview, it doesn't check the updates happening in the children.

**Comment by ogoffart** [comment] 2024-09-11 10:02
What version of the extension do you have?
Maybe this is the same as https://github.com/slint-ui/slint/issues/6063 which was in the nightly extension but fixed yesterday.

**Comment by ogoffart** [comment] 2024-09-11 10:03
> Additionally, if the parent component is used in preview, it doesn't check the updates happening in the children.

This works for me (testing with the printerdemo)
Could you give instructions on how to reproduce?

**Comment by dorukotiv** [comment] 2024-09-11 11:30
> What version of the extension do you have? Maybe this is the same as #6063 which was in the nightly extension but fixed yesterday.

it's not nightly. 
The version is 1.7.2

**Comment by ogoffart** [comment] 2024-09-11 11:40
I just checked an i realize that the bug was also present in 1.7.2
But it should be fixed now in the master  branch and should be in the next release.
Thanks for filling an issue!

**Closed by ogoffart** 2024-09-11 11:40 UTC
Labels: needs info, a:live preview
