### ISSUE TITLE
Using Path in an embedded project will result in a compilation error.

### ISSUE THREAD

**Issue by Song-aff** [slint-ui/slint#5092] opened 2024-04-18 06:30 UTC
When I try to add `Path` in main.slint, the compilation fails.
https://github.com/Song-aff/rs-esp32c3-slint-st7735-demo/tree/update_version

**Comment by ogoffart** [comment] 2024-04-18 10:04
Thanks for filling an issue.

What is the actual error?
I'm going to bet this is a duplicate of #2026 (which itself is a subset of #223)
So i'm going to close this issue as duplicated, assuming that.

Path is not working with the software renderer at the moment (tracked in #4178).

**Closed by ogoffart** 2024-04-18 10:04 UTC
