### ISSUE TITLE
Nullish coalescing operator (??) or somehow handling `void`

### ISSUE THREAD

**Issue by TheColorRed** [slint-ui/slint#6666] opened 2024-10-27 15:35 UTC
I am looking for something like a `Nullish coalescing operator (??)` (syntax taken from [JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing)). When trying to compare `void` I get the following error:

> Cannot convert void to length

I would like a way to to set a value to something default if the value is void or some type of nullish value, maybe either like this or using a ternary operator that just falls back to the else portion.

```slint
width: some-variable ?? 100%;
```

Here is what I tried:

```slint
export struct UIProject {
    zoom: float,
    image-width: length,
}

export global AppState {
    in-out property <[UIProject]> projects;
}

export component Stage inherits ScrollView {
    property <float> zoom: AppState.projects[AppState.active-project].zoom;
    property <length> image-width: AppState.projects[AppState.active-project].image-width;
    property <length> display-width: image-width * zoom;
    Rectangle {
        width: zoom > 0 ? display-width : 100%;
    }
}
```

**Comment by TheColorRed** [comment] 2024-10-27 16:27
After doing some research, it looks like the issue is with the `100%` at least in this case. changing the 100% to a `px` the error goes away. However, a px size is not what I am looking for.

**Comment by Enyium** [comment] 2024-10-28 04:52
Related: #5164

**Comment by ogoffart** [comment] 2024-10-28 08:51
Since we do not have the concept of null, i don't see how we could have the `??` operator at this point.
But having a concept of optional type would make sense, and as Enyium said, this is covered by #5154 , so i'm going to close this issue as duplicate of it.

**Closed by ogoffart** 2024-10-28 08:51 UTC
Labels: need triaging
