### ISSUE TITLE
Initial window content not rendered in window - WSL2

### ISSUE THREAD

**Issue by vdave007** [slint-ui/slint#5028] opened 2024-04-08 10:24 UTC
Using the https://github.com/slint-ui/slint-rust-template to create an app on WSL2, after starting up, the initial screen is not rendered inside the window but outside. 

![image](https://github.com/slint-ui/slint/assets/18720431/00aa814c-f4fb-4d33-9a35-9965491aa591)

Trying to interact with the content, is unsuccessful, in the example's case. Pressing the button doesn't work, and pressing inside the window just passes through.
The issue is solved when the window is moved or switching to other window and back, or just simply clicking on the window header.

Tested it on 2 different machine, and it reproduced on both, every time.
Not sure if this is a Slint issue or a WSL2 one.

**Comment by tronical** [comment] 2024-04-12 12:56
Duplicate of #4584

**Closed** 2024-04-12 12:56 UTC
