### ISSUE TITLE
How can i use async fn

### ISSUE THREAD

**Issue by xiaodusx1** [slint-ui/slint#1769] opened 2022-10-25 10:41 UTC
I need a login page.like this:
main_window.on_login( move|user,password|{
   let result=server.login(user,password).await?})

I use tokio::spawn,but it's too tremble.

Have a easy way to do it?

**Comment by ogoffart** [comment] 2022-10-26 07:01
We should offer API to run future in the Slint event loop.  This is already tracked in #757.

This comment explain a way to do it in the mean time:
https://github.com/slint-ui/slint/issues/747#issuecomment-995769853

Closing as duplicate of #757

**Closed by ogoffart** 2022-10-26 07:01 UTC
