### ISSUE TITLE
Popup close-on-click, disables possibility to close popup in lsp

### ISSUE THREAD

**Issue by qarmin** [slint-ui/slint#4037] opened 2023-11-29 20:55 UTC
Slint nightly LSP

Looks that problem only happens with LSP(not sure, but probably not always happens), but not with rust

popup.close() should always close popup

[CODE](https://slint.dev/releases/1.3.1/editor/?snippet=import+%7B+AboutSlint%2C+Button%2C+VerticalBox+%2C+ListView%2C+ScrollView%7D+from+%22std-widgets.slint%22%3B%0Acomponent+PopupComp+inherits+Rectangle+%7B%0A++++callback+show_popup%28%29%3B%0A++++callback+close_popup%28%29%3B%0A++++popup_window+%3A%3D+PopupWindow+%7B%0A++++++++close-on-click%3A+false%3B%0A++++++++width%3A+root.width%3B%0A++++++++height%3A+root.height%3B%0A++++++++VerticalLayout+%7B%0A++++++++++++width%3A+root.width%3B%0A++++++++++++height%3A+root.height%3B%0A++++++++++++Rectangle+%7B%0A++++++++++++++++background%3A+blue%3B%0A++++++++++++%7D%0A++++++++++++Button+%7B%0A++++++++++++++++text%3A+%22RRRRRR%22%3B%0A++++++++++++++++clicked+%3D%3E+%7B%0A++++++++++++++++++++debug%28%22Clicked%22%29%3B%0A++++++++++++++++++++popup_window.close_on_click+%3D+true%3B%0A++++++++++++++++++++popup_window.close%28%29%3B%0A++++++++++++++++++++popup_window.close_on_click+%3D+true%3B%0A++++++++++++++++%7D%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A++++show_popup+%3D%3E+%7B%0A++++++++popup_window.show%28%29%3B%0A++++%7D%0A++++close_popup+%3D%3E+%7B%0A++++++++popup_window.close%28%29%3B%0A++++%7D%0A%7D%0Aexport+component+Demo+%7B%0A++++width%3A+400px%3B%0A++++height%3A+500px%3B%0A++++in-out+property+%3Clength%3E+h%3A+120px%3B%0A++++VerticalLayout+%7B%0A++++++++Button+%7B%0A++++++++++++text%3A+%22Ok%22%3B%0A++++++++++++clicked+%3D%3E+%7B%0A++++++++++++++++debug%28%22Clicked2%22%29%3B%0A++++++++++++++++qq1.show_popup%28%29%3B%0A++++++++++++++++debug%28%22Clicked3%22%29%3B%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A++++in-out+property+%3Cstring%3E+h2%3A+%22120px%22%3B%0A%0A%0A++++qq1+%3A%3D+PopupComp+%7B%0A++++++++width%3A+root.width%3B%0A++++++++height%3A+root.height%3B%0A++++++++Button+%7B%0A++++++++++++text+%3C%3D%3E+h2%3B%0A++++++++%7D%0A++++%7D%0A%7D%0A&style=native)

Crash is reported in different issue - #4035

https://github.com/slint-ui/slint/assets/41945903/23d12624-4a1f-407b-9338-e1107e4681d3

**Comment by ogoffart** [comment] 2023-11-30 10:08
I think the issue preventing the button to work properly has been fixed in #4040

But I still can reproduce a crash (not the one from #4035) because ` popup_window.close_on_click = ...` crashes as the property doesn't really exist at runtime.

**Closed** 2023-12-12 20:51 UTC
