### ISSUE TITLE
bug: text is still blurry in low dpi

### ISSUE THREAD

**Issue by MicroCBer** [slint-ui/slint#4122] opened 2023-12-09 10:28 UTC
https://github.com/slint-ui/slint/pull/2618 This doesn't fix it for me.

Default(up) vs Skia(down)
![image](https://github.com/slint-ui/slint/assets/66859419/42f26965-0f44-4189-a86a-9ab298767d89)

my slint version is 1.3.2

**Comment by tronical** [comment] 2023-12-11 10:01
Yes, this is valid. As long as FemtoVG uses its own method of rasterising glyphs, it will always look different than Skia - which uses the "system" way of rasterising glyphs.

**Comment by tronical** [comment] 2023-12-11 10:01
Duplicate of #3742

**Closed by tronical** 2023-12-11 10:01 UTC

**Comment by MicroCBer** [comment] 2023-12-11 12:40
@Berrysoft told me that femtovg is actually rendering text pretty clearly when it's used directly. slint did something that makes it become blurry.

I'll test it when I'm free.

**Comment by codecat** [comment] 2023-12-24 16:59
I'm also seeing this behavior, which reminds me a lot of rendering text at sub-pixel coordinates. You can verify this using a hello world file:
```
export component TestWindow inherits Window {
	Text { text: "Hello, world"; }
}
```
If you resize the window, the text remains in the center, but it will be blurry at only certain (uneven?) window sizes. Tested on Fedora 39 w/ Gnome/Wayland.
