### ISSUE TITLE
PopupWindow bounds incorrect if sized and placed

### ISSUE THREAD

**Issue by flukejones** [slint-ui/slint#3712] opened 2023-10-20 00:13 UTC
The easiest way to demonstrate this issue is to create a window with:

1. A `TouchArea` covering full area and have `clicked` print something
2. Create a popup that is half the window size, and centered with `close-on-click` disabled
3. Click to the left and right

What appears to happen is that clicks outside the positive bounds are passed to the underlying touch area, while clicks in the negative bounds are completely blocked (and also not picked up by the popup).

**Comment by tronical** [comment] 2023-10-20 07:36
Thanks for the bug report. I tried to reproduce this but I haven't had any luck :(

This is the test case I made:

```
import { Button } from "std-widgets.slint";
export component App inherits Window {
    width: 400px;
    height: 400px;
    TouchArea {
        clicked => { debug("clicked"); }
    }
    Button {
        x: 0px; y: 0px;
        width: 80px;
        text: "Show popup";
        clicked => { p.show(); }
    }
    p := PopupWindow {
        x: 50px;
        width: 250px;
        height: 250px;
        Rectangle {
            background: green;
        }
        close-on-click: false;
    }
}
```

I ran it with `slint-viewer`. I pasted the same into [SlintPad](https://slintpad.com/?snippet=import+%7B+Button+%7D+from+%22std-widgets.slint%22%3B%0Aexport+component+App+inherits+Window+%7B%0A++++width%3A+400px%3B%0A++++height%3A+400px%3B%0A++++TouchArea+%7B%0A++++++++clicked+%3D%3E+%7B+debug%28%22clicked%22%29%3B+%7D%0A++++%7D%0A++++Button+%7B%0A++++++++x%3A+0px%3B+y%3A+0px%3B%0A++++++++width%3A+80px%3B%0A++++++++text%3A+%22Show+popup%22%3B%0A++++++++clicked+%3D%3E+%7B+p.show%28%29%3B+%7D%0A++++%7D%0A++++p+%3A%3D+PopupWindow+%7B%0A++++++++x%3A+50px%3B%0A++++++++width%3A+250px%3B%0A++++++++height%3A+250px%3B%0A++++++++Rectangle+%7B%0A++++++++++++background%3A+green%3B%0A++++++++%7D%0A++++++++close-on-click%3A+false%3B%0A++++%7D%0A%7D) and it "works" (the debug output is shown in the JavaScript console of the browser).

"Works" in the sense: When the popup is visible, any click on the popup itself is "eaten". When clicking outside the popup, it's closed.

**Comment by flukejones** [comment] 2023-10-24 21:36
@tronical I think this demonstrates it:

```slint
import { Button, VerticalBox } from "std-widgets.slint";
export component App inherits Window {
    width: 400px;
    height: 400px;
    private property <bool> fade-cover;
    
    VerticalBox {
        padding: 0px;
        Rectangle {
            Button {
                x: 0px; y: 0px;
                width: 80px;
                height: 30px;
                text: "Show popup";
                clicked => {
                    fade-cover = true;
                    p.show();
                }
            }
        }
    }

    if fade-cover: Rectangle {
        y: 30px;
        background: Colors.rgba(25,33,23,20);
        opacity: 0.7;
        TouchArea {
            height: 100%;
            width: 100%;
            clicked => {
                fade-cover = false;
                debug("clicked");
            }
        }
    }
    
    p := PopupWindow {
        x: 50px;
        y: 70px;
        width: 250px;
        height: 250px;
        Rectangle {
            background: green;
        }
        close-on-click: false;
    }
}
```

Clicking to the left and right of the green square (not on it) will show the issue I have. On the left and top you need to click twice, once to dismiss popup, and again to register click on touch area. On the right the click dismisses *and* registers on touch area. (it's the same with your example).

**Comment by tronical** [comment] 2023-10-25 07:44
Thanks for the updated example. I can reproduce it.

**Comment by tronical** [comment] 2023-10-26 16:24
Could you try the change in #3776 ?

The behavior is basically that a popup grabs the mouse. 

When `click-on-close` is true:
  * a click inside the popup is delivered, and then it is closed. 
  * a click outside the popup results in the popup being closed ("user discards")

When `click-on-close` is false:
 * a click inside the popup is delivered.
 * a click outside the popup is discarded.

**Comment by flukejones** [comment] 2023-10-26 21:05
@tronical looks like that solves the issue. I guess you also meant `close-on-click` :)

**Comment by tronical** [comment] 2023-10-26 21:34
Thanks for checking. And yes, I picked the wrong name oops :)

**Comment by tronical** [comment] 2023-10-27 09:50
Closing since #3776 implements the correct behavior, so that the bounds don't matter (apart from of course reaching TouchArea elements).

**Closed by tronical** 2023-10-27 09:50 UTC
Labels: bug, a:item tree
