### ISSUE TITLE
slint preview window not close-able on wayland

### ISSUE THREAD

**Issue by barafael** [slint-ui/slint#5617] opened 2024-07-12 16:48 UTC
The preview window, opened via vscode inline action, cannot be closed. When I close it by force, the LSP understandably crashes.

By 'forcibly closing', I mean the equivalent of xkill (meta-shift-esc on plasma by default).

Platform: KDE Plasma 6.0.5 / Wayland / Manjaro (`6.9.5-1-MANJARO (64-bit)`)

**Comment by tronical** [comment] 2024-07-12 17:32
Duplicate of #4225 . This is al long standing bug that's finally fixed, to be part of the upcoming 1.7 release. Or be daring and switch to the nightly lap (slint vscode extension nightly for example :)

**Comment by tronical** [comment] 2024-07-12 17:32
Duplicate of https://github.com/slint-ui/slint/issues/4225

**Closed by tronical** 2024-07-12 17:32 UTC
