### ISSUE TITLE
New number-getting props for `LineEdit`

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#5767] opened 2024-08-04 11:51 UTC
On `LineEdit`, you can specify `input-type: number;` or `input-type: decimal;`, but only retrieve the string `text`. If I want to bind a number type property to the `LineEdit`, I have to do something like this:

```slint
in-out property <float> value;
LineEdit {
    input-type: decimal;
    text: root.value;
    edited(text) => {
        root.value = text.to-float();
    }
}
```

Doesn't Slint's lazy property evaluation mean than it wouldn't hurt users of `text` `LineEdit`s, if `LineEdit` would simply provide two new properties to retrieve the text as `int` and `float`? Then, one could simply bind it like this:

```slint
in-out property <float> value;
LineEdit {
    input-type: decimal;
    decimal <=> root.value;
}
```

---

Having the properties `minimum` and `maximum` would also be good, so the output properties harmonize better with the business logic. If the value is smaller or larger, a reset to `minimum` or `maximum` would happen on `accepted` at the latest. Both properties could simply be floats, which would also be okay for `input-type: number;`, at least if we're not talking about numbers larger than the maximum safe integer of a float.

**Comment by tronical** [comment] 2024-08-05 13:32
Such a `LineEdit` sounds like more a `NumInput` type of widget than a textual `LineEdit` to me. Maybe this is a duplicate of #4288 ?

**Comment by Enyium** [comment] 2024-08-06 05:51
I was going from the fact that `LineEdit` provides `input-type` and found these proposals to just be consistent with it. If you'd provide a new specilized widget instead, fine. It would then also be useful, if it allowed to limit the number of displayed decimal places (with `round()`, I get programmatically set content like `3.299999999999`) and a (new?) locale concept that affects the decimal separator (`@tr()`'s app-wide brother `@locale-specific(decimal-seperator)`?). This widget or a Slint-internal prestage pendant of it could then be used as a basis for an improved `SpinBox` that also supports decimals with decimal step sizes (small and large step size, like with arrow key up and PageUp key).

**Comment by ogoffart** [comment] 2024-08-07 14:03
While I can see how this might be useful, I don't think it makes sense to have non-string property for the value in the LineEdit.
Which indeed means you can't have two way binding with a numerical property.

In the future, it will be possible to implement what you want with change event (#112).
Or if we had type conversion for two way bindings (#814)

I think right now the SpinBox has a `value` which is a number.

**Closed by ogoffart** 2024-08-07 14:03 UTC
