### ISSUE TITLE
The Button doesn't respects the `horizontal-stretch` property

### ISSUE THREAD

**Issue by ricvelozo** [slint-ui/slint#3037] opened 2023-07-03 23:08 UTC
The Button doesn't respects the `horizontal-stretch` property when there is a bigger sibling, like that Label:

```slint
import { Button, HorizontalBox, VerticalBox } from "std-widgets.slint";

export global App {
    pure callback quit();
}

export component Counter inherits Window {
    title: "Contador";
    out property <int> count: 5;
    states [
        counting when count > 1: { label.text: "Encerra em \{count} cliques."; }
        ending when count == 1: { label.text: "Encerra no próximo clique!"; }
    ]

    HorizontalBox {
        alignment: center; // Same as `stretch` in this case
        VerticalBox {
            alignment: center;
            label := Text { font-size: 18px; }
            Button {
                horizontal-stretch: 0; // Shouldn't stretch, but does
                text: "Fechar";
                primary: true;
                clicked => {
                    root.count -= 1;
                    if (root.count == 0) {
                        App.quit();
                    }
                }
            }
        }
    }
}
```

Using Fedora 38, GNOME 44/X11. The `Cargo.toml`:

```toml
[dependencies.slint]
version = "1.1"
default-features = false
features = ["compat-1-0", "std", "backend-winit", "renderer-winit-femtovg"]

[build-dependencies]
slint-build = "1.1"
```

**Comment by ogoffart** [comment] 2023-07-04 09:02
Thanks for filling an issue.
Maybe the documentation should be improved. Or possibly more flag should be added to the layouts.

The layout always stretch the widgets in the orthogonal direction.

So to do what you try to achieve, you need to add another HorizontalLayout:
[example](https://slint.dev/releases/1.1.0/editor/?snippet=import+%7B+Button%2C+HorizontalBox%2C+VerticalBox+%7D+from+%22std-widgets.slint%22%3B%0A%0Aexport+global+App+%7B%0A++++pure+callback+quit%28%29%3B%0A%7D%0A%0Aexport+component+Counter+inherits+Window+%7B%0A++++title%3A+%22Contador%22%3B%0A++++out+property+%3Cint%3E+count%3A+5%3B%0A++++states+%5B%0A++++++++counting+when+count+%3E+1%3A+%7B+label.text%3A+%22Encerra+em+%5C%7Bcount%7D+cliques.%22%3B+%7D%0A++++++++ending+when+count+%3D%3D+1%3A+%7B+label.text%3A+%22Encerra+no+pr%C3%B3ximo+clique%21%22%3B+%7D%0A++++%5D%0A%0A++++HorizontalBox+%7B%0A++++++++alignment%3A+center%3B+%2F%2F+Same+as+%60stretch%60+in+this+case%0A++++++++VerticalBox+%7B%0A++++++++++++alignment%3A+center%3B%0A++++++++++++label+%3A%3D+Text+%7B+font-size%3A+18px%3B+%7D%0A++++++++++++HorizontalLayout+%7B%0A++++++++++++++++alignment%3A+center%3B%0A++++++++++++++++Button+%7B%0A++++++++++++++++++++%2F%2F+horizontal-stretch%3A+0%3B+%2F%2F+not+needed%0A++++++++++++++++++++text%3A+%22Fechar%22%3B%0A++++++++++++++++++++primary%3A+true%3B%0A++++++++++++++++++++clicked+%3D%3E+%7B%0A++++++++++++++++++++++++root.count+-%3D+1%3B%0A++++++++++++++++++++++++if+%28root.count+%3D%3D+0%29+%7B%0A++++++++++++++++++++++++++++App.quit%28%29%3B%0A++++++++++++++++++++++++%7D%0A++++++++++++++++++++%7D%0A++++++++++++++++%7D%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A%7D)

**Comment by ogoffart** [comment] 2024-01-19 12:01
Duplicate of https://github.com/slint-ui/slint/issues/2587

**Closed by ogoffart** 2024-01-19 12:01 UTC
Labels: a:layouts
