### ISSUE TITLE
[slint-lsp/vscode] action to open the element's document at the cursor's position

### ISSUE THREAD

**Issue by abique** [slint-ui/slint#5083] opened 2024-04-16 19:57 UTC
Hi,

Please could you add a vscode action to open the element's document at the cursor's position?
Thanks :+1: 

Alex

**Comment by abique** [comment] 2024-04-16 20:20
I can't navigate to `TouchArea`'s definition.

**Comment by abique** [comment] 2024-04-16 20:20
In case of built-in I'd like to open the documentation on the web.

**Comment by ogoffart** [comment] 2024-04-16 21:12
Unfortunately, there is no protocol for opening documentation in the LSP.
We could add tooltips. 
But anyway, this issue is the same as #4263 then. So closing as duplicate of #4263

**Closed by ogoffart** 2024-04-16 21:12 UTC
