### ISSUE TITLE
Nested Flickables don't work

### ISSUE THREAD

**Issue by MattMoszczynski** [slint-ui/slint#1349] opened 2022-06-15 21:21 UTC
I experienced an issue that if we create a nested Flickable (one Flickable inside another), the inner Flickable won't scroll. My current implementation of the code: https://github.com/Project-Trains/launcher/blob/master/src/ui/market.slint. 

Here's a simplified example:
```css
Item := Rectangle {
    vertical-stretch: 1;
    width: 300phx;

    Rectangle { 
        height: parent.height;
        width: parent.width - 20phx;
        border-radius: 20phx;
        background: #161a1f;
        drop-shadow-color: #0000006e;
        drop-shadow-blur: 12phx;
        clip: true;

        Image {
            source: @image-url("../assets/devlog.jpg");
            image-fit: cover;
            height: parent.height;
            width: parent.width;
        }
    }
}

Test := Rectangle {
    vertical-stretch: 1;
    horizontal-stretch: 1;
    clip: true;

    Flickable {
        interactive: false;
        
        VerticalLayout {                

            Flickable {
                interactive: false;
                height: 180phx;

                HorizontalLayout {
                    clip: true;

                    Item {}
                    Item {}
                    Item {}
                    Item {}
                    Item {}
                    Item {}
                    Item {}
                    Item {}
                    Item {}
                    Item {}
                }
            }
        }
    }
}

```

**Comment by ogoffart** [comment] 2022-06-27 08:27
Thanks for your bug report

I cannot reproduce the problem.
In your example, you have `interactive:false;` on your Flickable, which of course means it doesn't flick.
If i remove that, then it flicks correctly (see [live editor](https://slint-ui.com/releases/0.2.4/editor/?snippet=Item+%3A%3D+Rectangle+%7B%0A++++vertical-stretch%3A+1%3B%0A++++width%3A+300phx%3B%0A%0A++++Rectangle+%7B+%0A++++++++height%3A+parent.height%3B%0A++++++++width%3A+parent.width+-+20phx%3B%0A++++++++border-radius%3A+20phx%3B%0A++++++++background%3A+%23161a1f%3B%0A++++++++drop-shadow-color%3A+%230000006e%3B%0A++++++++drop-shadow-blur%3A+12phx%3B%0A++++++++clip%3A+true%3B%0A%0A++++++++Image+%7B%0A++++++++++++source%3A+%40image-url%28%22..%2Fassets%2Fdevlog.jpg%22%29%3B%0A++++++++++++image-fit%3A+cover%3B%0A++++++++++++height%3A+parent.height%3B%0A++++++++++++width%3A+parent.width%3B%0A++++++++%7D%0A++++%7D%0A%7D%0A%0ATest+%3A%3D+Rectangle+%7B%0A++++vertical-stretch%3A+1%3B%0A++++horizontal-stretch%3A+1%3B%0A++++clip%3A+true%3B%0A%0A++++Flickable+%7B%0A++++++++%2F%2Finteractive%3A+false%3B%0A++++++++%0A++++++++VerticalLayout+%7B++++++++++++++++%0A%0A++++++++++++Flickable+%7B%0A++++++++++++++++%2F%2Finteractive%3A+false%3B%0A++++++++++++++++height%3A+180phx%3B%0A%0A++++++++++++++++HorizontalLayout+%7B%0A++++++++++++++++++++clip%3A+true%3B%0A%0A++++++++++++++++++++Item+%7B%7D%0A++++++++++++++++++++Item+%7B%7D%0A++++++++++++++++++++Item+%7B%7D%0A++++++++++++++++++++Item+%7B%7D%0A++++++++++++++++++++Item+%7B%7D%0A++++++++++++++++++++Item+%7B%7D%0A++++++++++++++++++++Item+%7B%7D%0A++++++++++++++++++++Item+%7B%7D%0A++++++++++++++++++++Item+%7B%7D%0A++++++++++++++++++++Item+%7B%7D%0A++++++++++++++++%7D%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A%7D) )

Is there another way to reproduce the problem?

**Comment by ogoffart** [comment] 2022-10-27 07:44
I'm closing this issue since i cannot reproduce it.  Maybe this was caused by `interactive:false`.
Feel free to comment on it if you want it to be re-opened.

**Closed by ogoffart** 2022-10-27 07:44 UTC
Labels: bug
