### ISSUE TITLE
Cannot use `self.width`/`self.height` in `PopupWindow`'s coordinate binding

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#3289] opened 2023-08-17 06:40 UTC
The following snippet fails to compile:

```
export component Demo {
    popup := PopupWindow {
        x: root.width / 2 - self.width;
        width: 100px;
        height: 100px;
        Rectangle {        
            background: red;
        }
    }
    init => {
        popup.show();
    }
}
```

For `PopupWindow` the error message `Cannot access the inside of a PopupWindow from enclosing component` is shown.

I suspect that this is related to the popup lowering pass where coordinate properties are pulled out?

**Comment by ogoffart** [comment] 2023-08-17 06:47
duplicate of #1056

**Comment by tronical** [comment] 2023-08-17 06:47
Duplicate of #1056

**Closed by ogoffart** 2023-08-17 06:47 UTC
Labels: bug, a:language-slint
