### ISSUE TITLE
Const propagation is thinking model content is const when it shouldn't

### ISSUE THREAD

**Issue by kanashimia** [slint-ui/slint#5249] opened 2024-05-16 12:45 UTC
### Background:

I've been implementing node graph, with code based on this: https://github.com/slint-ui/slint/discussions/3608#discussioncomment-7207488

And there seems to be this one line: `nodes[idx] = n;`, the problem occurs when you remove it.

### Problem:

Basically in slint-lsp or slint-viewer when you try to move Node then Link attached to it doesn't update, it looks like this: 

![image](https://github.com/slint-ui/slint/assets/56224949/4a1d3f7b-0baa-4bae-a9ea-e1c7d74f061f)

But when you try to move it in the slintpad or in the compiled rust project with slint builder it looks like this:

![image](https://github.com/slint-ui/slint/assets/56224949/d3f7e14a-96e2-4e8f-b83e-e9183ded0393)

### Expected:

Both behave the same, I expected the second outcome.

### Test:

[[SlintPad preview]](https://slintpad.com/?snippet=struct+Node+%7B+x%3A+length%2C+y%3A+length%2C+text%3A+string+%7D%0Astruct+Link+%7B+x1%3A+length%2C+x2%3A+length%2C+y1%3A+length%2C+y2%3A+length+%7D%0A%0Aexport+component+Demo+inherits+Window+%7B%0A++++preferred-height%3A+500px%3B%0A++++preferred-width%3A+500px%3B%0A++++in-out+property+%3C%5BNode%5D%3E+nodes%3A+%5B%0A++++++++%7B+text%3A+%22Node1%22%2C+x%3A+120px%2C++y%3A+235px%2C+%7D+%2C%0A++++++++%7B+text%3A+%22Node2%22%2C+x%3A+350px%2C++y%3A+150px%2C+%7D+%2C%0A++++++++%7B+text%3A+%22Node3%22%2C+x%3A+300px%2C++y%3A+350px%2C+%7D+%2C%0A++++%5D%3B%0A%0A++++function+create-link%28a%3Aint%2C+b%3Aint%29-%3E+Link+%7B%0A++++++++return+%7B+x1%3A+nodes%5Ba%5D.x%2C+y1%3A+nodes%5Ba%5D.y%2C+x2%3A+nodes%5Bb%5D.x%2C+y2%3A+nodes%5Bb%5D.y+%7D%3B%0A++++%7D%0A++++in+property+%3C%5BLink%5D%3E+links%3A+%5B+create-link%281%2C2%29%2C+create-link%280%2C2%29+%5D%3B%0A%0A++++for+l+in+links+%3A+path+%3A%3D+Path+%7B%0A++++++++viewbox-width%3A+self.width+%2F1px%3B%0A++++++++viewbox-height%3A+self.height+%2F1px%3B%0A++++++++stroke%3A+orange%3B%0A++++++++stroke-width%3A+2px%3B%0A++++++++MoveTo+%7B+x%3A+l.x1+%2F+1px%3B+y%3A+l.y1+%2F+1px%3B+%7D%0A++++++++LineTo+%7B+x%3A+l.x2+%2F+1px%3B+y%3A+l.y2+%2F+1px%3B+%7D%0A%0A++++%7D%0A%0A++++for+n%5Bidx%5D+in+nodes+%3A+Rectangle+%7B%0A++++++++background%3A+gray%3B%0A++++++++x%3A+n.x+-+self.width%2F2%3B%0A++++++++y%3A+n.y+-+self.height%2F2%3B%0A++++++++width%3A+l.preferred-width%3B%0A++++++++height%3A+l.preferred-height%3B%0A++++++++border-radius%3A+3px%3B%0A++++++++l+%3A%3D+HorizontalLayout+%7B%0A++++++++++++padding%3A+15px%3B%0A++++++++++++Text+%7B+text%3A+n.text%3B+%7D%0A++++++++%7D%0A++++++++TouchArea+%7B%0A++++++++++++moved+%3D%3E+%7B%0A++++++++++++++++if+%28self.pressed%29+%7B%0A++++++++++++++++++++n.x+%2B%3D+self.mouse-x+-+self.pressed-x%3B%0A++++++++++++++++++++n.y+%2B%3D+self.mouse-y+-+self.pressed-y%3B%0A++++++++++++++++++++%2F%2F+nodes%5Bidx%5D+%3D+n%3B%0A++++++++++++++++%7D%0A++++++++++++%7D%0A++++++++++++mouse-cursor%3A+move%3B%0A++++++++%7D%0A++++%7D%0A%7D&style=cupertino-dark)

To test you can just open SlintPad, and verify that it works, than save that file and open it on local machine with slint-viewer and verify that it doesn't work, uncomment the line, it will work.

### Conclusion:

Is this a bug, or a skill issue? In any ways it is weird that the behaviour is different.

It looks like some update dependency isn't being set when it should, or in reverse.

APPENDIX 1:
What I actually wanted is to move out Node from the loop into its own definition, but than there is a different problem with
two-way bindings not supported, may be related here? That seems to only be implementable by passing whole array and index as properties, which is annoying. if you have idea on how to do it in a different way please say.

APPENDIX 2:
Actually after looking into I think the issue is that one way binding acts like a two way binding on cargo run and slintpad?
Here is the link: [SlintPad weird example 2](https://slintpad.com/?snippet=struct+Node+%7B+x%3A+length%2C+y%3A+length%2C+text%3A+string+%7D%0Astruct+Link+%7B+x1%3A+length%2C+x2%3A+length%2C+y1%3A+length%2C+y2%3A+length+%7D%0A%0Aexport+component+Node+inherits+Rectangle+%7B%0A++++in-out+property+%3C%5BNode%5D%3E+nodes%3B%0A++++in+property+%3Cint%3E+idx%3B%0A++++background%3A+gray%3B%0A++++x%3A+nodes%5Bidx%5D.x+-+self.width%2F2%3B%0A++++y%3A+nodes%5Bidx%5D.y+-+self.height%2F2%3B%0A++++width%3A+l.preferred-width%3B%0A++++height%3A+l.preferred-height%3B%0A++++border-radius%3A+3px%3B%0A++++l+%3A%3D+HorizontalLayout+%7B%0A++++++++padding%3A+15px%3B%0A++++++++Text+%7B+text%3A+nodes%5Bidx%5D.text%3B+%7D%0A++++%7D%0A++++TouchArea+%7B%0A++++++++moved+%3D%3E+%7B%0A++++++++++++if+%28self.pressed%29+%7B%0A++++++++++++++++nodes%5Bidx%5D.x+%2B%3D+self.mouse-x+-+self.pressed-x%3B%0A++++++++++++++++nodes%5Bidx%5D.y+%2B%3D+self.mouse-y+-+self.pressed-y%3B%0A++++++++++++%7D%0A++++++++%7D%0A++++++++mouse-cursor%3A+move%3B%0A++++%7D%0A%7D%0A%0Aexport+component+Demo+inherits+Window+%7B%0A++++preferred-height%3A+500px%3B%0A++++preferred-width%3A+500px%3B%0A++++in-out+property+%3C%5BNode%5D%3E+nodes%3A+%5B%0A++++++++%7B+text%3A+%22Node1%22%2C+x%3A+120px%2C++y%3A+235px%2C+%7D+%2C%0A++++++++%7B+text%3A+%22Node2%22%2C+x%3A+350px%2C++y%3A+150px%2C+%7D+%2C%0A++++++++%7B+text%3A+%22Node3%22%2C+x%3A+300px%2C++y%3A+350px%2C+%7D+%2C%0A++++%5D%3B%0A%0A++++function+create-link%28a%3Aint%2C+b%3Aint%29-%3E+Link+%7B%0A++++++++return+%7B+x1%3A+nodes%5Ba%5D.x%2C+y1%3A+nodes%5Ba%5D.y%2C+x2%3A+nodes%5Bb%5D.x%2C+y2%3A+nodes%5Bb%5D.y+%7D%3B%0A++++%7D%0A++++in+property+%3C%5BLink%5D%3E+links%3A+%5B+create-link%281%2C2%29%2C+create-link%280%2C2%29+%5D%3B%0A%0A++++for+l+in+links+%3A+path+%3A%3D+Path+%7B%0A++++++++viewbox-width%3A+self.width+%2F1px%3B%0A++++++++viewbox-height%3A+self.height+%2F1px%3B%0A++++++++stroke%3A+orange%3B%0A++++++++stroke-width%3A+2px%3B%0A++++++++MoveTo+%7B+x%3A+l.x1+%2F+1px%3B+y%3A+l.y1+%2F+1px%3B+%7D%0A++++++++LineTo+%7B+x%3A+l.x2+%2F+1px%3B+y%3A+l.y2+%2F+1px%3B+%7D%0A%0A++++%7D%0A%0A++++for+n%5Bidx%5D+in+nodes+%3A+Node+%7B%0A++++++++nodes%3A+nodes%3B%0A++++++++idx%3A+idx%3B%0A++++%7D%0A%7D&style=cupertino-dark)
You see, it has `nodes: nodes;` there right, so in the slintpad it propagates the modified state to the parent, but in the slint-lsp it doesn't, when you change it to `nodes <=> nodes;` then it works in both.

**Comment by tronical** [comment] 2024-05-16 14:54
Wow, this is unexpected. Good that you found a workaround - this seems like a bug to me.

**Comment by ogoffart** [comment] 2024-06-04 07:39
Thanks for filling a bug.

Here is a smaller testcase:

```
export component Btn {
  in-out property <[int]> model;
  width: 30px;
  height: 30px;
  Rectangle {
    background: red;
  }
  TouchArea {
    clicked => {
      model[0] += 1;
    }
  }
}

export component MainWindow inherits Window {
    preferred-height: 500px;
    preferred-width: 500px;
    //in-out     //changing the property to in-out fixes it in the viewer
    property <[int]> model: [42];

    // adding a change in the same component fixes the problem
    // TouchArea {  enabled: false; clicked => { model[0] += 10; }  }

    Btn{ model: model; }
    Text { text: model[0]; }
}
```

In that testcase, clicking on the red rectangle doesn't increment the text value.
That's because the const propagation phase thinks this is a const model as it doesn't "see" the change.
Changing the property to be `in` fixes it on the viewer but not on the LSP or slintpad because they add an extra layer so the property is still considered constant.
Adding a setter somewhere does workaround the problem though, as then the compiler sees it changes.


The problem is that the const propagation think that the model is const because nothing gets assigned to it. But this analysis is incorrect for model that are assigned to other property and then get modified trough it.

**Closed** 2024-06-04 13:24 UTC
Labels: bug, a:compiler
