### ISSUE TITLE
The live preview on rust template project crashes the language server

### ISSUE THREAD

**Issue by SidneyCogdill** [slint-ui/slint#6829] opened 2024-11-19 05:39 UTC
### Bug Description

https://github.com/user-attachments/assets/19b276b5-0fe4-4db0-b591-22a1c3deda0d

Reproducible steps:

1. Download the rust template project on https://docs.slint.dev/latest/docs/slint/src/quickstart/getting_started
2. Extract it and open it with VS Code (assuming the rust-analyzer and slint extensions are already installed)
3. Open `ui/app-window.slint` file, click on the `Show Preview` button on top of `AppWindow`
4. In the Live-Preview window, click on the `Interact` button, then click on `Increase value` button
5. Now toggle the `Edit` mode on
6. Slint LSP crashes

```
thread 'main' panicked at D:\a\slint\slint\internal\core\model.rs:928:38:
already borrowed: BorrowMutError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 1:25:41 PM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug. Please open an issue on https://github.com/slint-ui/slint/issues
```

### Reproducible Code (if applicable)

```slint
https://github.com/slint-ui/slint-rust-template/archive/refs/heads/main.zip
```

### Environment Details

- Slint Version: 1.8.0
- Platform/OS: Windows 11
- Programming Language: Rust
- Backend/Renderer: Don't know

### Product Impact

I didn't expect LSP to crash on a hello world project provided by the slint tutorial, so I guess that's a **blocker** issue.

**Comment by ogoffart** [comment] 2024-11-19 07:57
Thanks for filing a bug report. It looks like this is a duplicate of issue https://github.com/slint-ui/slint/issues/6529 and https://github.com/slint-ui/slint/issues/3214, it should be fixed in the master branch already.
I'm going to close this issue as duplicate, but thanks anyway for reporting.

**Closed by ogoffart** 2024-11-19 07:57 UTC
Labels: bug, need triaging
