### ISSUE TITLE
Documentation website scrolls away from HTML anchor

### ISSUE THREAD

**Issue by alexeyabel** [slint-ui/slint#6449] opened 2024-10-04 18:13 UTC
When using the documentation and jumping to a specific chapter, e.g. [TouchArea](https://releases.slint.dev/1.8.0/docs/slint/src/language/builtins/elements.html#toucharea), the website first jumps to the correct anchor, i.e. the section of  TouchArea but then after a few seconds scrolls back twice. This happens both when the URL is entered directly into the address bar or when I use the search.

Observed with Firefox 130.0.1 and Chromium Version 129.0.6668.70. See video for demonstration. I am not scrolling at all while I move the mouse in circles or at any other point in time.

https://github.com/user-attachments/assets/7d457511-0f1f-4793-bc93-3463cda2af6a

**Comment by Enyium** [comment] 2024-10-04 18:15
Dupe of #6023.

**Closed as completed** 2024-10-04 18:22 UTC
