### ISSUE TITLE
Open two different components

### ISSUE THREAD

**Issue by quiet-feifei** [slint-ui/slint#3429] opened 2023-09-08 05:14 UTC
Sorry, my English is not very good,

How can I export two components in the main.slint file.
```
component TestWin inherits Window {
    
}

component TestWin1 inherits Window {
    
}


export { TestWin,TestWin1 }
```
But this only introduces the last component in main.rs.
```
 TestWin::new();
   |     ^^^^^^^^ use of undeclared type `TestWin`
```

**Comment by tronical** [comment] 2023-09-08 08:46
Yes, sadly this is not possible at the moment :(

**Comment by tronical** [comment] 2023-09-08 08:46
Duplicate of #784

**Closed** 2023-09-08 08:46 UTC
