### ISSUE TITLE
 Memory increases greatly  when using default-font-family

### ISSUE THREAD

**Issue by zhoujun681** [slint-ui/slint#3808] opened 2023-10-30 14:54 UTC
Memory increases a lot when use default-font-family 

Memory usage increases greatly when using Chinese fonts, even if the system has this font.
Increased by 100m in win7 -_-.
Can I load a certain character into memory only when I need to use it, instead of loading the entire font library into memory at once?
`
    export component HelloWorld inherits Window{
        default-font-family: "微软雅黑";
...
}
`

**Comment by tronical** [comment] 2023-11-03 09:13
Thank you for the report. It's understandable that a Chinese font has more characters and is larger on disk. But using it should not increase the amount of heap memory used. Fonts should be mapped from disk and not contribute to the heap.

How do you measure the memory sage?

Would it be possible for you to use [VMMap](https://learn.microsoft.com/en-gb/sysinternals/downloads/vmmap) and see how the different memory mappings change for your app when enabling and disabling the use of Chinese fonts?

**Comment by tronical** [comment] 2023-11-03 09:15
For example, the widgets gallery for me maps two .ttf file into memory. Those don't contribute to the heap though, they merely occupy address space.

<img width="794" alt="Screenshot 2023-11-03 at 10 14 51" src="https://github.com/slint-ui/slint/assets/1486/dc5834a1-e283-41c7-80cd-d8bfe99b9412">

**Comment by tronical** [comment] 2024-02-06 13:45
Closing this as it's not clear what's actionable for us to do here, and I couldn't reproduce this issue either.

**Closed by tronical** 2024-02-06 13:45 UTC
Labels: needs info, a:text
