### ISSUE TITLE
Provide function to copy string to clipboard

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#6503] opened 2024-10-10 01:11 UTC
It would be useful if you could copy text to the clipboard directly from Slint code. Text input widgets already support copying with Ctrl+C anyways, so why not make it available as a function? My app has an error message widget, and a button to copy the message to the clipboard would be useful.

**Comment by tronical** [comment] 2024-10-10 05:56
Duplicate of #2570

**Closed by tronical** 2024-10-10 05:56 UTC
