### ISSUE TITLE
Image does not show gif image getting Error decoding embedded image: The image format Gif is not supported

### ISSUE THREAD

**Issue by learncodingforweb** [slint-ui/slint#4846] opened 2024-03-14 13:02 UTC
```
Image {
            width: 320px;
            source: @image-url("../assets/walk.gif");
            image-fit: ImageFit.fill;
        }
```
getting error
Error decoding embedded image: The image format Gif is not supported
thread 'main' panicked at ..\.cargo\registry\src\index.crates.io-6f17d22bba15001f\i-slint-core-1.5.0\graphics\image.rs:838:13:
internal error: embedded image data is not supported by run-time library
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\dfmd_display.exe` (exit code: 101)

But I am able to display jpg image

**Comment by tronical** [comment] 2024-03-14 13:43
Duplicate of #2081

**Comment by tronical** [comment] 2024-03-14 13:44
Yes, it's true - .gif images are not supported right now. That said, I supposed we shouldn't panic.

**Comment by tronical** [comment] 2024-03-14 22:05
Resolved the panic. Animated gif support is part of #2081. If you're happy with a static .gif file, then you can add a dependency to the image crate and enable the gif feature.

**Closed by tronical** 2024-03-14 22:05 UTC
