### ISSUE TITLE
Layout changes reset maximized state under Windows 10

### ISSUE THREAD

**Issue by tp971** [slint-ui/slint#2904] opened 2023-06-15 23:24 UTC
It seems that anything that changes the layout (like width/height of any component of conditional components) resets the maximized stated of the window. Here is an example:

```rs
fn main() {
    MainWindow::new().unwrap().run().unwrap();
}

slint::slint! {
	import { Button, HorizontalBox, LineEdit, VerticalBox } from "std-widgets.slint";
	
	export component MainWindow {
		VerticalBox {
			HorizontalBox {
				edit := LineEdit {}
				Button {
					text: "Set";
					clicked => {
						text.text = edit.text;
					}
				}
				text := Text {
					text: "Hello world!";
				}
			}
		}
	}
}
```

When running this program, maximizing the window and pressing the button, the window gets un-maximized, but keeps its full size (and moves slightly bottom right).

**Comment by ogoffart** [comment] 2023-06-16 08:05
I can't reproduce that on Linux (x11 plasma, winit or qt) so i'm going to assume this might be platform specific.

What backend/renderer are you using?  I'm assuming winit.  This might be a bug in winit.

**Comment by ogoffart** [comment] 2024-01-19 11:59
Fixed in most recent winit.

**Closed by ogoffart** 2024-01-19 11:59 UTC
Labels: bug, a:platform-windows
