### ISSUE TITLE
Setting LineEdit's text value programmatically does not update the cursor's position.

### ISSUE THREAD

**Issue by kivimango** [slint-ui/slint#3188] opened 2023-07-29 11:30 UTC
OS: Linux Manjaro KDE
Backends: winit, x11, software-renderer

MRE:

```rust
slint::slint! {
    import { LineEdit, HorizontalBox} from "std-widgets.slint";
    export component Demo inherits Window {
    width: 640px;
    height: 320px;
    forward-focus: input;

    public function set_input_value(new_value: string) {
        input.text = new_value
    }

    HorizontalBox {
        input := LineEdit {
            input-type: text;
            height: 63px;
            }
        }
    }
}

fn main() {
    let window = Demo::new().unwrap();
    let new_value = slint::SharedString::from("test_value");
    window.invoke_set_input_value(new_value);
    window.run().unwrap();
}
```

Expected behavior:
the cursor should be at the end of the new value instead of the start.

**Comment by FloVanGH** [comment] 2023-07-31 06:43
@kivimango thank your for the report. A workaround for this is to dispatch  key events instead. This works if the `LineEdit` has focus:

```rust
fn main() {
    let window = Demo::new().unwrap();
    insert_text(window.as_weak(), "test_value");
    window.run().unwrap();
}

fn insert_text(window: &MainWindow, text: &str) {
    for c in text.chars() {
        window.window().dispatch_event(slint::platform::WindowEvent::KeyPressed { text: c.into() });
        window
            .window()
            .dispatch_event(slint::platform::WindowEvent::KeyReleased { text: c.into() });
    }
}
```

**Comment by tronical** [comment] 2024-02-06 13:31
Duplicate of #331

**Closed by tronical** 2024-02-06 13:31 UTC
Labels: a:text
