### ISSUE TITLE
`spawn_local` polls only once (Rust)

### ISSUE THREAD

**Issue by E-Mans-Application** [slint-ui/slint#4232] opened 2023-12-28 23:36 UTC
Hello,

I can't get function `slint::spawn_local` to work properly. The future is only executed entirely if it is immediately ready.
Otherwise, it is only polled once when it is created, then it seems it is never woken up again.

The following code works (it prints "step1" and "step2")
```rust
slint::Timer::single_shot(Duration::from_micros(100), || {
    slint::spawn_local(async {
        println!("step1");
        async { }.await;
        println!("step2");
    })
    .unwrap();
});
MainWindow::new().unwrap().run().unwrap();
```

But the following code only prints "step1". The event loop runs fine because the window stays visible.
```rust
slint::Timer::single_shot(Duration::from_micros(100), || {
    slint::spawn_local(async {
        println!("step1");
        tokio::time::sleep(core::time::Duration::from_millis(100)).await;
        println!("step2");
    })
    .unwrap();
});
MainWindow::new().unwrap().run().unwrap();
```

Is it a bug, or am I doing something wrong?
What do I have to change to make my future run to completion?

**Comment by ogoffart** [comment] 2023-12-29 08:06
I wonder if the problem is that tokio::time::sleep assumes a tokio runtime, but you've got a "Slint" runtime in the main thread.

**Comment by E-Mans-Application** [comment] 2023-12-29 19:32
Indeed, Tokio does not seem to be compatible with Slint.

I replaced `tokio::time::sleep` with `async_std::task::sleep`, and everything seems to be working now!

I was using `#[tokio::main] async fn main { .. }`, but I guess it was not enough for the future to be polled properly.

Thank you for helping me to figure this out.

**Comment by ogoffart** [comment] 2023-12-31 15:56
> Tokio does not seem to be compatible with Slint.

The thing is that the tokio executor don't run in the Slint thread. The Slint thread uses the backend's event loop which is, for example winit. You can use Tokio and Slint, but the Tokio things needs to be in a different thread.

I'll close this issue since this seems to be fixed for you.

**Closed by ogoffart** 2023-12-31 15:56 UTC
