### ISSUE TITLE
The previewer in vscode show different from the real application

### ISSUE THREAD

**Issue by Zhou-Pixel** [slint-ui/slint#2187] opened 2023-02-06 02:49 UTC
this is the code:
# //hello.slint
```js
import { Button, GridBox } from "std-widgets.slint";
export component Example inherits Window {
    preferred-width: 800px;
    preferred-height: 480px;
    Button {
        property <int> counter: 3;
        clicked => { self.counter += 3 }
        text: self.counter * 2;
        font-size: 100px;
    }
}
```
# //main.rs
```rust
slint::include_modules!();
fn main() {
    Example::new().run();
}
```

# privewer show:
![image](https://user-images.githubusercontent.com/72525794/216871952-454d0fb7-1627-4641-ab73-97d0146c4d94.png)
# real application:
![image](https://user-images.githubusercontent.com/72525794/216872027-a1b8f22b-f9ea-4edc-b986-85d0ab5693aa.png)

**Comment by tronical** [comment] 2023-02-06 08:55
I can reproduce this, it seems to be related to the native style somehow.

**Comment by tronical** [comment] 2023-02-24 11:01
We discussed this and decided to change the default size to be preferred when not in layouts (like in this case), so we'd like to address this issue as part of #2284. Therefore closing as duplicate.

**Closed by tronical** 2023-02-24 11:01 UTC
Labels: bug, backend-qt
