### ISSUE TITLE
feat: enter and leave animation

### ISSUE THREAD

**Issue by MicroCBer** [slint-ui/slint#4123] opened 2023-12-09 10:33 UTC
It would be nice to have convenient enter and leave animation, like svelte ones.

https://learn.svelte.dev/tutorial/transition

**Comment by ogoffart** [comment] 2023-12-11 14:11
Thanks for filling an issue.

This is a duplicate of https://github.com/slint-ui/slint/issues/3258

**Closed by ogoffart** 2023-12-11 14:11 UTC
