### ISSUE TITLE
Request for Canvas API Support

### ISSUE THREAD

**Issue by chonwhite** [slint-ui/slint#3734] opened 2023-10-23 11:20 UTC
I recently discovered Slint and was impressed by its capabilities. However, upon further investigation, I noticed that it lacks support for the Canvas API. I would like to inquire about any plans to add support for the Canvas API in Slint.

Currently, the absence of Canvas API support poses limitations on creating complex custom widgets. Without access to the low-level canvas API, it becomes challenging to achieve highly customized widgets and implement advanced visual effects.

I kindly request the inclusion of Canvas API support in Slint. By integrating the Canvas API, developers would gain the ability to create intricate custom widgets and leverage low-level canvas operations for advanced visual effects. This enhancement would greatly enhance the flexibility and versatility of Slint as a GUI library.

**Comment by tronical** [comment] 2023-10-23 12:16
duplicate of #432

I agree, an imperative "painting" API that operates on a Canvas, that itself is blended into the UI is desirable to have.

**Closed by tronical** 2023-10-23 12:16 UTC

**Comment by chonwhite** [comment] 2023-10-23 13:16
Thank you for the reply, I can go with the sixtyfps::Image solution at the moment, can you point me to any example or documentation, A C++ example would be preferable.

**Comment by tronical** [comment] 2023-10-23 13:21
> Thank you for the reply, I can go with the sixtyfps::Image solution at the moment, can you point me to any example or documentation, A C++ example would be preferable.

The [C++ documentation of `slint::Image`](https://slint.dev/releases/1.1.1/docs/cpp/api/structslint_1_1Image#_CPPv4N5slint5ImageE) has a small snippet. Once you have that `slint::Image`, you can set it on an `in property<image>` that's exposed in your Slint code, for example in the root component or in a global.

**Comment by chonwhite** [comment] 2023-10-24 08:02
Cool!, just tried it, and works perfectly, another question is should I update the whole window when I want to redraw the image content? Seems inefficient to me, but can't find a partial redraw request API in the Image class.

**Comment by tronical** [comment] 2023-10-24 11:24
Indeed, there's no support for partial updates on `slint::Image` yet.
