### ISSUE TITLE
in .slint file,I can use @tr() macro to translate language, how to get translated strings in rust code?

### ISSUE THREAD

**Issue by ryanjackgit** [slint-ui/slint#3388] opened 2023-08-31 03:56 UTC
For example,  use @tr("hello") in .slint file.  in rust code,how to do it?

**Comment by ogoffart** [comment] 2023-08-31 06:14
There are a few crates that do it. For example with https://crates.io/crates/tr  you can use `tr!("hello")`

**Comment by ryanjackgit** [comment] 2023-09-01 05:25
on windows 10, build gettext-sys error ,  #3307

**Comment by ogoffart** [comment] 2024-01-19 12:18
Duplicate of https://github.com/woboq/tr/issues/10 and https://github.com/Koka/gettext-rs/issues/12 and #3307

**Closed by ogoffart** 2024-01-19 12:18 UTC
Labels: a:platform-windows, upstream
