### ISSUE TITLE
Animations started from init callback don't start if  update_timers_and_animations was not called before creating the component

### ISSUE THREAD

**Issue by MiSimon** [slint-ui/slint#2809] opened 2023-06-02 08:00 UTC
I am trying to write a simple application with slint (version 1.0.2) in a no_std environment.
I encountered some issues as i trief to implement a login form (text fields and buttons).

1) The cursor at the current text position is not rendered.
If the text field gets the focus, the _slint::platform::duration_until_next_timer_update()_ method starts to return Some(...) values but the _self.window.has_active_animations()_ method still returns false.

2) The password field does not replace the input with dots like it does in other environments.

3) If i add an animation to a Widget the animation is not performed.

If i run the same example using the preview function everything works as expected.

Is there something besides _create_window_adapter_ and _duration_since_start_ that has to be implemented to solve this issues?

**Comment by ogoffart** [comment] 2023-06-02 11:35
> 1. The cursor at the current text position is not rendered.

This should be fixed in master already (#2710 and #2730)

> 2. The password field does not replace the input with dots like it does in other environments

Also fixed in master


> 3. If i add an animation to a Widget the animation is not performed.
> Is there something besides create_window_adapter and duration_since_start that has to be implemented to solve this issues?

Yes, you must implement `duration_since_start` otherwise and call  `slint::platform::update_timers_and_animations` .
Without re-implementing `duration_since_start`, Slint doesn't know that time has elapsed and will therefore not animate things.

**Comment by MiSimon** [comment] 2023-06-02 11:52
Thank you for your answer, you are correct 1&2 are fixed in the master branch.

I implemented `duration_since_start` and call `slint::platform::update_timers_and_animations` in my loop. The text cursor is now blinking but the animation is still not performed.

This is my loop:
```
slint::platform::update_timers_and_animations();
self.dispatch_input_events();
self.renderer.render(&mut self.window);    
```
and this my test object:
```
// inside component that inherits Window
Rectangle {
	width: 50px;
	height: 50px;
                        
	x: parent.width/2 - self.width/2;

	background: red;

	animate background { duration:10000ms;easing:ease; }
	init => {
		self.background = #ff0000;
		self.background = #00ff00;
	}
}
```

**Comment by MiSimon** [comment] 2023-06-05 06:27
In the preview the init animation is performed but not in the build, but if i start the animation after the first cycle of the main loop the animations are performed in the build.

**Comment by ogoffart** [comment] 2024-01-16 15:15
Looking at this, I think the problem is that slint::platform::update_timers_and_animations was not called before the component was created, and so by the time of the first frame, a "very long time" has passed and all animation started by init are finished.

**Closed** 2024-01-24 08:34 UTC
Labels: bug
