### ISSUE TITLE
Winit-FemtoVG renderer wraps image inappropriately

### ISSUE THREAD

**Issue by dgulotta** [slint-ui/slint#6878] opened 2024-11-23 21:25 UTC
### Bug Description

If there is an image inside of a HorizontalBox, then the Winit-FemtoVG renderer renders the leftmost line of pixels on the right, and the bottommost line of pixels on the top.

Screenshot:
![screenshot](https://github.com/user-attachments/assets/7dfc7bec-8e68-4f2e-95ed-f036a8bc602b)

Source image:
![gradient](https://github.com/user-attachments/assets/5475e7c3-9f5a-4e73-a8ab-ba07869dacfc)

This issue does not happen in the qt, winit-software, or winit-skia renderers (although the winit-software renderer crashes with an index out of bounds error if I try to resize the window).

### Reproducible Code (if applicable)

```slint
import { HorizontalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    HorizontalBox {
        Image {
            source: @image-url("res/gradient.png");
        }
    }
}
```

### Environment Details

- Slint Version: 1.8.0
- Platform/OS: Void Linux; Xfce 4.18 on X11
- Programming Language: Rust
- Backend/Renderer: Winit+FemtoVG

**Comment by ogoffart** [comment] 2024-11-27 14:31
I believe that might be a duplicate of https://github.com/slint-ui/slint/issues/6268  (fixed in master in b42840ee85684bd31e13058af808f39877b67ca6)

**Comment by ogoffart** [comment] 2024-11-27 14:34
Could you check with the master branch (Slint 1.9.0)  ([instructions](https://github.com/slint-ui/slint/releases/tag/nightly)) and see if this is still a problem?

**Comment by dgulotta** [comment] 2024-11-27 14:49
It does appear to be fixed in master. (Although the software renderer still crashes when resizing the window - should I file a separate issue for that?)

**Comment by tronical** [comment] 2024-11-27 14:54
> It does appear to be fixed in master.

Great, thanks for checking!

>  (Although the software renderer still crashes when resizing the window - should I file a separate issue for that?)

Yes, that would be very much appreciated.

**Closed by tronical** 2024-11-27 14:54 UTC
Labels: bug, a:renderer-femtovg, need triaging
