### ISSUE TITLE
Incorrect font weight with certain font

### ISSUE THREAD

**Issue by MiKom** [slint-ui/slint#2315] opened 2023-03-02 12:57 UTC
## Steps to reproduce

(related to https://github.com/slint-ui/slint/issues/2314)

Run the following slint file under winit and qt back ends (version from 0.3.5 windows binary release) :
```
import "./PretendardVariable.ttf";

export component AppWindow inherits Window {
    width: 1024px;
    height: 768px;

    background: black;

    Text {
        font-size: 96px;
        font-family: "Pretendard Variable";
        font-weight: 700;
        color: white;
        text: "Test test";
    }
}
```
Tested on windows 10.
Font file: `PretendardVariable.ttf` from https://github.com/orioncactus/pretendard/releases/download/v1.3.6/Pretendard-1.3.6.zip

## Expected result
Text is rendered with proper weight

## Actual result
Winit: 
![image](https://user-images.githubusercontent.com/104767/222433847-91df0b9d-a666-4643-a7ed-c10c265480fa.png)

Qt:
![image](https://user-images.githubusercontent.com/104767/222435036-2fccde08-4780-4df6-b7b9-911820f292e6.png)

**Comment by MiKom** [comment] 2023-03-02 13:07
In windows font dialog, with weight of 700 this font looks as follows:
![image](https://user-images.githubusercontent.com/104767/222437115-086573c0-87d2-4cec-bdb3-3025cac356ed.png)

**Comment by tronical** [comment] 2024-01-19 13:00
Duplicate of #3742

**Closed by tronical** 2024-01-19 13:00 UTC
Labels: a:text
