### ISSUE TITLE
Resizing a window re-evaluates all properties

### ISSUE THREAD

**Issue by Tmpod** [slint-ui/slint#4585] opened 2024-02-08 16:35 UTC
It seems that, when resizing a window, all properties are re-evaluated. This means, all models, all lengths, everything, is reset to their "original" values. This makes it impossible to persist, for example, element resizing when resizing a window, because the elements will just default back to their initial sizes. Additionally, `ListView`s and the likes have their item delegates reinitialized everytime (you can observe this through some `debug` calls in the `init` callback), which can be potentially expensive.

Is this intended?

**Comment by ogoffart** [comment] 2024-02-08 16:55
Only the properties that depends on the size are re-evaluated.
Do you have an example of code where this is a problem?

**Comment by Tmpod** [comment] 2024-02-08 17:40
Right, I see. I now understand why Slint is reinitializing my elements when the window is resized: they are in a container which is conditionally created based on an expression with width properties.

I've made a small reproducer, [here](https://slint.dev/releases/1.4.1/editor/?snippet=import+%7B+ListView+%7D+from+%22std-widgets.slint%22%3B%0A%0Aexport+component+Example+inherits+Window+%7B%0A++++if+self.width+%3E+200px%3A%0A++++ListView+%7B%0A++++++++for+data+in+%5B%0A++++++++++++%7B+name%3A+%22foo%22+%7D%2C%0A++++++++++++%7B+name%3A+%22bar%22+%7D%2C%0A++++++++++++%7B+name%3A+%22baz%22+%7D%2C%0A++++++++++++%7B+name%3A+%22bork%22+%7D%0A++++++++%5D+%3A+Text+%7B%0A++++++++++++text%3A+data.name%3B%0A++++++++++++init+%3D%3E+%7B+debug%28data.name%29%3B+%7D%0A++++++++%7D%0A++++%7D%0A%7D%0A&style=native). The debug message obviously doesn't show in SlintPad (off-topic, but maybe that could be added?), but it works with `slint-viewer`.

That example also demonstrates another issue, but perhaps I should open a different issue for it: the `init` callback only seems to be triggered for the first element in a `ListView`  ("foo" in that case), never for the others. This works as expected in `ScrollView`, however.

**Comment by ogoffart** [comment] 2024-02-09 08:21
Thanks for the reproducer.
I'm going to close this as a duplicate of https://github.com/slint-ui/slint/issues/3953
But thanks anyway for reporting the bug.

**Closed by ogoffart** 2024-02-09 08:21 UTC
