### ISSUE TITLE
Generate code in src directory rather than in build output?

### ISSUE THREAD

**Issue by changhe3** [slint-ui/slint#2711] opened 2023-05-10 06:17 UTC
Currently rust analyzer cannot inspect the generated code thus cannot autocomplete for us. Generating the code in actually source directory would easily fix that, also allowing us to easily inspect the generated code. It doesn't even have to be a proc-macro. A binary in lieu of pyuic.exe in PyQt would work well too.

**Comment by ogoffart** [comment] 2023-05-15 06:15
I think rust-analyzer should find the generated from the build directory as well, the same way.
If rust-analyzer don't find the source code in the build dir, this sounds like a bug in rust-analyzer.  It works for me with vscode when using the `slint::include_modules!()` macro.

In general, the build shouldn't write into the source dir. But we could offer options to run the compiler manually. Actually, the slint-compiler can do that if you run it manually.

**Comment by ogoffart** [comment] 2023-05-15 06:16
Do you have any way to reproduce the problem with rust-analyzer?

**Comment by asuper0** [comment] 2023-05-29 02:44
Currently they work fine for me. Try to "activate" the rust-analyzer by writing some code manually, then the rust-analyzer may find the right generated file. This also helps when you change the .slint file and rebuild.

**Comment by ogoffart** [comment] 2023-05-30 17:16
I'm going to close this issue because we shouldn't generate the files in the source directory.
But thanks anyway for taking the time to fill a bug.

An option to be able to specify the path in slint_build would make sense though.

**Closed by ogoffart** 2023-05-30 17:16 UTC
