### ISSUE TITLE
Property "default-font-family" is not effective by using slint-lsp 

### ISSUE THREAD

**Issue by gy0801151351** [slint-ui/slint#6143] opened 2024-09-14 07:19 UTC
Hello! During my tests, I found the property "default-font-family" of Window can affect other widgets font.
But when I preview it by slint-lsp, it doesn't work.

The version of slint is "1.7.2".

**Comment by tronical** [comment] 2024-09-14 07:35
Yes, this is unfortunately a Duplicate of #4298

**Comment by tronical** [comment] 2024-09-14 07:36
Duplicate of #4298

**Closed by tronical** 2024-09-14 07:36 UTC
