### ISSUE TITLE
Single touch taps not registering as clicks with winit + x11

### ISSUE THREAD

**Issue by andrew-otiv** [slint-ui/slint#6219] opened 2024-09-19 13:03 UTC
Ubuntu 24.04.1 with default Gnome Desktop.
Slint is version="1.7.1", default_features=False, features=["backend-winit","renderer-femtovg","compat-1-2"])

On Ubuntu with Wayland, single taps behave like single clicks in our slint application, as expected. If we switch to x11 (because we have different unrelated problems in wayland), we observe:
* single taps never register as clicks, but seem to change either focus or hover (not sure)
* double taps with a single finger register as a click... maybe one time in 30
* tapping with two fingers registers reliably as a single click

We have replicated the behavior both with a btronics touchscreen and a laptop with a wacom touchscreen, but we don't believe it to be a linux or a driver problem. We inspected the kernel events generated on the two devices, and they only differ in that the btronics sends timestamp events.

If the cause were in Slint's handling of winit events, or in our application code, I would expect the failure to be present with both Wayland and X11. Since it's the role of winit to abstract between wayland and x11 (and windows and mac), this is likely a bug in winit. That said, winit exposes different events for mouse and touch to applications, and hiding platform differences can be subtle. Slint could have a bug related to a valid sequence of events that only X11 throws.

**Comment by ogoffart** [comment] 2024-09-19 14:31
I tried to reproduce on my computer, but touch is correctly recognized as a click for me.
As you say this is most likely an issue upstream. So i'll close the issue in this repository.

Also, are other (non-winit-based) application working fine? Asking because this might also depends on how the X11 server is configured.

**Closed** 2024-09-19 14:31 UTC
Labels: a:backend-winit, upstream

**Comment by andrew-otiv** [comment] 2024-09-19 14:41
@ogoffart can you tell us more about your environment? We are a bit desperate to find an environment where touch is working for our demo tomorrow.

**Comment by ogoffart** [comment] 2024-09-19 19:50
I'm using Archlinux. With X11 in its almost default config. On a Dell XPS 13 laptop with touch-screen

**Comment by andrew-otiv** [comment] 2024-09-20 10:02
Thanks @ogoffart!

I was able to demonstrate that the issue is indeed in the X11 layer.

For posterity, if your (not necessarily winit based) app isn't working with a touchscreen on X11 Ubuntu, you can try the following as a temporary workaround:

Hit Apple/Windows/Command/Super + Alt + 8 to enter some kind of zoom mode
While in the zoom mode, zoom all the way out by hitting Apple/Windows/Command/Super + Alt + "-" repeatedly
confirm with xev that you get button press and button release events
Do NOT exit the zoom mode

Alternatively, to automate this you can run the following commands in the shell:

gsettings set org.gnome.desktop.a11y.magnifier mag-factor 1.00
gsettings set org.gnome.desktop.a11y.applications screen-magnifier-enabled true

Fun story, after struggling with this for two days, this workaround was discovered when a colleague literally dropped his keyboard on the floor!
