### ISSUE TITLE
TextEdit does not display input when running for the first time on Windows 2022

### ISSUE THREAD

**Issue by zhoujun681** [slint-ui/slint#6440] opened 2024-10-03 16:04 UTC
TextEdit does not display input when running for the first time on Windows 2022. It needs to be maximized and restored to return to normal.There is no such problem in win7 and win10.By the way,both software and skia are not work.
![image](https://github.com/user-attachments/assets/f995de70-c188-4f85-aa18-0d59622b5fca)

**Comment by tronical** [comment] 2024-10-04 07:00
Duplicate of #5206

**Closed** 2024-10-04 07:01 UTC
