### ISSUE TITLE
Outwards-propagation of `preferred-...` hindered

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#6315] opened 2024-09-25 22:37 UTC
Consider [this SlintPad demo](https://slintpad.com/?snippet=import+%7B+Button+%7D+from+%22std-widgets.slint%22%3B%0A%0A%2F%2F+Move+lines+with+Alt%2Bvertical+arrow+keys.%0Aexport+component+Demo+%7B%0A++++r+%3A%3D+Rectangle+%7B%0A++++++++width%3A+self.preferred-width%3B%0A%0A++++++++r2+%3A%3D+Rectangle+%7B%0A++++++++++++preferred-width%3A+100px%3B+%2F%2F+Moving+up+makes+it+propagate.%0A++++++++++++%2F*%0A++++++++++++*%2F+%2F%2F+Moving+down%2C+removing+%60Button%60%2C+makes+it+propagate.%0A++++++++++++Button+%7B%7D%0A++++++++%7D%0A++++%7D%0A%0A++++Text+%7B%0A++++++++text%3A+%28%0A++++++++++++%22%5C%7Br.width+%2F+1px%7D%2C+%22+%2B%0A++++++++++++%22%5C%7Br2.width+%2F+1px%7D%2C+%22+%2B%0A++++++++++++%22%22%0A++++++++%29%3B%0A++++%7D%0A%7D%0A&style=native) (see comments):

```slint
import { Button } from "std-widgets.slint";

// Move lines with Alt+vertical arrow keys.
export component Demo {
    r := Rectangle {
        width: self.preferred-width;

        r2 := Rectangle {
            preferred-width: 100px; // Moving up makes it propagate.
            /*
            */ // Moving down, removing `Button`, also makes it propagate.
            Button {}
        }
    }

    Text {
        text: (
            "\{r.width / 1px}, " +
            "\{r2.width / 1px}, " +
            ""
        );
    }
}
```

**Comment by ogoffart** [comment] 2024-09-26 07:25
I think it's a duplicate of https://github.com/slint-ui/slint/issues/6285

**Comment by ogoffart** [comment] 2024-09-26 07:31
I confirm that https://github.com/slint-ui/slint/pull/6306 fixes the problem. Will incorporate this testcase in the test.
Closing as duplicate pf #6285 for now.

**Closed by ogoffart** 2024-09-26 07:31 UTC
Labels: a:layouts, need triaging
