### ISSUE TITLE
The button component cannot be displayed in Chinese

### ISSUE THREAD

**Issue by rulongche** [slint-ui/slint#5456] opened 2024-06-22 10:07 UTC
After setting the height of the button component, the preview display is normal, but the Chinese language cannot be displayed after publication
`Button {
                            text: "复制";
                            height: 24px;
                        }`
![screenshot-20240622-180601](https://github.com/slint-ui/slint/assets/76928602/13507d23-1b43-42fe-9053-864f41250ada)

**Comment by ogoffart** [comment] 2024-06-24 06:40
Thanks for filling an issue. Looks like a font problem.
What platform and renderer are you using?

**Comment by humbinal** [comment] 2024-07-10 16:15
> Thanks for filling an issue. Looks like a font problem. What platform and renderer are you using?

I had the same problem, windows and winit  renderer.

**Comment by tronical** [comment] 2024-07-11 06:19
Duplicate of #2029

**Closed by tronical** 2024-07-11 06:19 UTC
Labels: bug, a:text
